### ISSUE TITLE
Command List Command

### ISSUE THREAD

**Issue by xCryptic** [aura-project/aura#109]
I just noticed we don't have a command that shows a list of commands and what they do. I know you can just look at the config file, but what about the players on random servers? They won't know where to look.

So there should be a `>help` or `>commands` to show a list of commands (what they do and how to use them) based on the user's auth level.

**Comment by Cosrnos** [comment]
This does sort of link back to #77 since the problem is how many commands are in the game. It wouldn't be a bad idea to "Organize" commands by type so you can do something like 

    > commands

    Available commands by type: `item` `player` `stat` `movement`

    > commands item

    drop - Drops an item at your current position
    item - places an item in your inventory
    info - finds item info

etc.

**Comment by Xcelled** [comment]
I think #77 has broadened now - I'll retitle it and let's move all discussions there.

**Comment by exectails** [comment]
Certainly not a bad suggestion, especially with normal players in mind, who won't get to see *all* the commands, but only the ones enabled for their authority level. Those players will probably never get a long list.

GMs/devs on the other hand would get a huge list, but I wonder if that's even a problem. You could categorize them, but really, they should have a list of commands anyway imo, without having to look them up with `help`. And for usage instructions all you need to do is type only the command, it will then fail and show you how to use it.

As Cryptic said, such a command would be most useful for normal players, on a random server.

**Comment by ImaBrokeDude** [comment]
For something like this, would it do better to make the command type something that is set when the command is added so that the command itself will be more maintainable?

Something like

```
public enum CommandCategory : byte
{
	Item,
	Player,
	Stat,
	Movement
}

Add(50, 50, "item", "<id|name> [amount|color1 [color2 [color 3]]]", CommandCategory.Item, HandleWhere);
```

To accomplish:

```
> commands

Available commands by type: `item` `player` `stat` `movement`

> commands item

drop - Drops an item at your current position
item - places an item in your inventory
info - finds item info
```

**Comment by DeleteIT** [comment]
`>help`
Check what commands the user has the privileges for, list all commands that meet criteria.
Do so to trade/whisper chat, with brief description + available aliases.

Alternatively, just list the basic commands they have access to, in trade/whisper chat, give a system message to prompt them to look at the trade/whisper channel, and then just allow users to do `>help [command name]` for the basic outline of what it does, and what aliases it has.

Preferably group them by the level those commands would be, user/gm/admin.


Anything else requires too much effort, and will ultimately prove confusing/time consuming to update, as very few commands are clearly one thing.

**Comment by Seeker1437** [comment]
@DeleteIT 
This was my attempt at it based off your recommendation, is there any recommended improvements?

https://youtu.be/n__H6XZCa2I

**Comment by Seeker1437** [comment]
I tried

**Comment by exectails** [comment]
>Do so to trade/whisper chat

Why did you suggest doing it in those chats, why not the normal one? I find the thought of having to switch chats just to see the output of the command kinda irritating.

>Preferably group them by the level those commands would be, user/gm/admin.

I think we can safely ignore this. What does grouping accomplish? The target audience for this command will probably be normal players, who want to see what commands are available to them, which will usually be in the user or VIP category, but those categories are not set in stone, they're just a convention nobody has to stick to.

I could have a server with 10 user groups, no GM groups, and one dev group. I could put GM commands in the user group, like warp, and GMs might fail to notice that it's in the user group and think they don't have access to it. I think hard-coding groups doesn't work too well with the authority system.

>with brief description + available aliases

With the amount of text dozens or hundreds of commands can produce, outputting descriptions or even more information is tricky. At some point you might even reach the limit of the chat log box, and all that text will be difficult to read.

Maybe the easiest solution would be to just list them, ordered alphabetically, for a quick look up of whether you can use certain commands.

```text
>help
Commands available to you: cp, distance, partysize, where

>help cp
Displays your Combat Power.
Usage: cp
```

Wanting to know which commands are available is something very common when joining a random server, but it won't be often that you want to read through the descriptions of all commands.

**Comment by Seeker1437** [comment]
What would have been the way tjat you would have done it?

**Comment by exectails** [comment]
If I would have had a specific idea I would have stated so or would have done it myself.

**Comment by Seeker1437** [comment]
Oh, that make sense really My big thing was presenting them, so I am kinda unskilled, I didnt like the idea of them being a big block of text. I didnt think it would make sense to list them once per line either, I normally see help outs display both a description and usage, but that doesnt fit well in the console

**Comment by Seeker1437** [comment]
The minecraft output system seemed okay to me where many of the more advanced help command did go by page

**Comment by Seeker1437** [comment]
but you are right, some of them havr like 27 pages of commands and that's ugly

**Comment by Seeker1437** [comment]
Okay after regaining the ability to think.

I guess I have a couple things I wanted to say during the process I didn't

When I attempted to group by auth you said a person could change the auth, does this mean that the auth levels are not reflected in the command dictionary based off the config file? If so then the auth grouping would not be wrong as I would just be pulling the value the admin configured the auth numbers to be.

In regards to the page system I was thinking the same if commands kept growing it wouldn't be so great whoever a quick adjustment to the `countPerPage` could reduce our current commands of commands to 2 pages (count per page could be 50 without being cut off). I actually considered maybe splitting into two commands because people do have the freedom of putting whatever they want for their commands.

Splitting would only be needed if there was a page system, so that makes the page system less attractive to me.

> ```>help
Commands available to you: cp, distance, partysize, where
```

In the case where I might make 100 commands available to the average user, this can be pretty hard to read.

I guess my insistence with grouping and such comes from not being able to see very well in the first place but I wanted to also make is seem well developed with many edge cases thought up... this was the better place to do that I see now.

I really don't want to waste your time. These are just my thoughts.

Thanks for taking the time to read.

**Comment by exectails** [comment]
>does this mean that the auth levels are not reflected in the command dictionary based off the config file

I clearly stated the reason, if I'm a GM who's used to warp being auth 50, and suddenly it's 0, or 99, or god knows what, people could think they don't have access to the command, because it's missing from the group they're used to have it in.

>In the case where I might make 100 commands available to the average user, this can be pretty hard to read.

No matter what you do, if there are 100 commands available it will always be hard to read. That's not the average use-case for this command though. It's not what it's for.

**Comment by Seeker1437** [comment]
> I clearly stated the reason, if I'm a GM who's used to warp being auth 50, and suddenly it's 0, or 99, or god knows what, it could be 500, because someone is using the auth system in a different way, people could think they don't have access to the command, because it's missing from the group they're used to have it in.

My thing with this rebuttle is that the way I wrote the command, you can't see commands you don't have access to. In other words, of tthey can see the command, they can use the command to some degree. In a situation where they are on a server where the system is different should not have such an effect because, no matter what, if you can see if you can use it.

Even im the case where you don't see a command in the list but you know it exists, you would be able to use `help command` and it would tell you "Unknown command or the command is not available to you.".

**Comment by DeleteIT** [comment]
Exec, if you used the server often enough to know the groupings for commands, why would you even need the help command?

If I were used to warp being something I have access to, why would that even register when looking at commands, if I used the help command?

**Comment by exectails** [comment]
>no matter what, if you can see if you can use it

Maybe we should look at an example. You're a player who wants to know whether you can use the `foobar` command. Go.

```text
Auth 0
========================
a, ac, adipiscing, aliquam, aliquet, amet, ante, arcu, at, auctor,
augue, bibendum, blandit, consectetur, consequat, curabitur, dapibus,
diam, dictum, dignissim, dolor, donec, egestas, eget, eleifend, elit,
in, inceptos, interdum, justo, lacus, laoreet, leo, ligula, litora, luctus,
maecenas, magna, malesuada, massa, mattis, mauris, metus, mollis, nam, nec

Auth 1
========================
enim, erat, eros, est, et, etiam, eu, euismod, ex, facilisis, fames,
nec, neque, netus, nibh, nisi, nisl, non, nulla, nunc, odio, orci, ornare,
pellentesque, placerat, porttitor, posuere, praesent, pretium, proin

Auth 2
========================
hendrerit, iaculis, id, imperdiet, in, integer, interdum, ipsum, justo,
lacus, lectus, leo, libero, ligula, lobortis, lorem, magna, malesuada

Auth 3
========================
faucibus, fermentum, feugiat, finibus, fringilla, gravida, habitant,
ut, vehicula, vel, velit, vitae, viverra, volutpat

Auth 4
========================
class, congue, consectetur, consequat, conubia, convallis, cras, curabitur,
purus, quam, quisque, risus, rutrum, sagittis, sapien, scelerisque, sed,
semper, senectus, sit, sodales, sollicitudin, suscipit, suspendisse

Auth 10
========================
ac, accumsan, ad, aenean, aliquam, aliquet, amet, ante, aptent, at, augue,
cursus, dapibus, dolor, donec, duis, egestas, eget, erat, est, et, etiam,
eu, felis, fermentum, foobar, gravida, hendrerit, himenaeos, id, imperdiet,
in, inceptos, interdum, justo, lacus, laoreet, leo, ligula, litora, luctus,
maecenas, magna, malesuada, massa, mattis, mauris, metus, mollis, nam, nec,

Auth 20
========================
a, ac, adipiscing, aliquam, aliquet, amet, ante, arcu, at, auctor,
augue, bibendum, blandit, consectetur, consequat, curabitur, dapibus,
tellus, tempus, tincidunt, torquent, tortor, tristique, turpis, ultrices,
ut, vehicula, vel, velit, vitae, viverra, volutpat
```

You can always *search* for it, but why make it hard?

>The only reason to not group the commands IMO is simply because it's not a concurrent user experience between servers

That's basically what I was trying to say, the GM thing was just the only example I could think of at the time where this could irritate someone.

>I only suggested the grouping aspect because I thought it might be useful to segregate commands as they grow in "severity", to lend a sense of, I don't know, responsibility or weight to them.

Right, you've been concerned about something like this before when we talked about the shutdown command.

I see your point, but how likely is it that someone with GM or even Dev rights goes in there, gets a list of commands, and just tries every one without checking what it does first? And why would you give someone access to dangerous commands who would do something like that? That's the only situation I can think of where giving them a hint as to how powerful a command is would be important.

But then you have the flexible auth again, what if all commands are made available at auth 40+? Someone who's used to all dangerous things being 50+ could think "Oh great, all safe to play around with!"

**Comment by Seeker1437** [comment]
>Which is absolutely useless as a response.
If I previously had access to a command, but don't now, what am I supposed to do?
Assume that it's no longer a command? That the server is defective? That I was demoted?
What is the point of this ambiguity when I can literally just go look at the source code repository and look to see what the commands are?

Fair point, another thing I noticed, my system does not take into the account the possibility that you might easier access to commands on other people than yourself.

```user's auth: 50
foo 60, 20
bar 40, 60
```

only `bar` would show even though on have valid access to foo on another person.

Past that oversight on my part...

> >The only reason to not group the commands IMO is simply because it's not a concurrent user experience between servers
>That's basically what I was trying to say, the GM thing was just the only example I could think of at the time where this could irritate someone.

Now as you speak of how things could be totally different, I can see how narrow minded I'm being.

I say, lets go with just listing them alphabetically. If an admin wants to group them on their server, they can just override the command from a script.

**Comment by YaibaToKen** [comment]
May I suggest something? not sure if any of you ever played minecraft, but what they do with their command list is line them up by alphabetical order, divide the number of commands by the number of commands to show in each page and finally print the commans for the page selected. So if I wanted to see the first page I could either use >help or >help 1, with 1 being the argument for page number.

Not sure if I'm being clear or anything >.> also, you might want to place a short description for each command, a single line would do. That space can be used to warn players/admins/gms of the dangers of the command.

So I assume each line would read:
"command" - "short description";
Or something similar.

And feel free to disregard the suggestion entirely if you feel it doesn't fill your need ;)

**Comment by Seeker1437** [comment]
see #240

**Comment by exectails** [comment]
@YaibaToKen My concern with pages and including descriptions is that it's a huge wall of text. I don't know how many commands a typical Minecraft server has, but with dozens or even hundreds of commands (we don't have control over that) that's not a quick reference what is available to you anymore, it becomes a manual, pages over pages.

I don't know much about the Minecraft scene, but it might also differ from typical pservers a little, in that most pservers have proper websites where they can put up the "manual", instead of just sharing IPs somewhere, where you have no idea what to expect. In most cases you also only have the standard commands, just with varying authority levels.

In my experience the typical use-case for such a help command is to see which commands are available to you, to have a quick overview, not to read through all the descriptions time and time again.

Maybe you guys have a different opinion? I just want us to think about what we expect from this command. Would *you* really browse through hundreds of commands in-game, with or without pages, in the limited chat log? Say you would do it once, when you're new to Aura, would you ever do it again?

**Comment by YaibaToKen** [comment]
@exectails I see your point... would it be possible to simply list each command with the respective auth levels and passing a command name as an argument for the help command provide a description for it? That way, you can avoid cluttering the chat log. And the last pserver I ran for minecraft had about 30 pages of commands, so I'd say a bit short of 100 commands total. Though, listing all the commands should also have an easy to identify separator, so people can easily skim the text and notice when a command ends and another begins.

@Seeker1437 yeah, I only noticed that issue after commenting, sorry about that.

**Comment by exectails** [comment]
>sorry about that.

No worries, nobody expects you to dig through pull requests.

>list each command with the respective auth levels and passing a command name as an argument for the help command provide a description for it? 

Yea, that's basically my idea, see my post above: https://github.com/aura-project/aura/issues/109#issuecomment-193981397

**Comment by YaibaToKen** [comment]
@exectails well, I see no actual problems with it :)

**Comment by exectails** [comment]
I've now implemented it the way it was discussed here, a simple list on `>help`, description, alias, and usage information on `>help command`. If anyone has any more ideas or suggestions, please post here or make a pull request. While this is how I think the command should work like, based on what I predict to be the typical usage, I'm not the one who is gonna use it, so I value your input.
