### ISSUE TITLE
99% success rate a dirty lie?

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#122]
I managed to fail 3/5 at 99% when making thick thread balls. I'm not sure if i'm just very unlucky or that the 99% success rate is a lie. Has the additional successrates from weather, party or production mastery been added?

**Comment by exectails** [comment]
Looks like party bonus hasn't been added for those skills yet, only for Tailoring and Blacksmithing. But I just realized, I forgot to check the success chances for the production skills. If they differ between the skills, we might have a problem there =| I've based them on a thread from Mabination about refining, because I couldn't find any other information.

I'll take a look at them later. Thankfully, I can overwrite what the client displays, if we can't find accurate formulas .__.

**Comment by Pegwald** [comment]
I believe in you, Exec :>

**Comment by exectails** [comment]
Checked Handicraft, the success chance is definitely wrong. The chance on Aura is about 20-30% lower than what the client displays.
