### ISSUE TITLE
No stamina consumption with normal attacks

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#125]
I just noticed that a warrior can run dungeons endlessly without consuming a single stamina pot. Reason? Normal attacks don't consume stamina. Right now I'm using bastard swords and I'm paying attention to my stamina bar which isn't really moving downwards to the left. Instead it's full, even when I'm hungry it doesn't consume extra stamina.

**Comment by exectails** [comment]
Hm, I don't remember implementing it, and I don't see it anywhere, so it's probably completely missing. I'll put it on the backlog, not really a bug per se.

If someone wants to take a stab at it, the stamina usage information is in the item data, I think we have to just reduce the stamina in Combat Mastery.

**Comment by exectails** [comment]
I think our GetRndLeftHandDamage might be wrong. How much damage is the off-hand supposed to do? We only add general race damage and damage bonuses to the weapon damage for the right hand, the left hand uses only the weapon damage. I guess that can't be right, especially since you're supposed to do bare hand damage with 0 stamina? Is that the case for the off-hand as well?
