### ISSUE TITLE
Giant hair features aren't completely working

### ISSUE THREAD

**Issue by xeroplz** [aura-project/aura#130]
If you choose a giant hairstyle with, say, a beard, the beard doesn't show on the actual character. I've known about that for a while but just decided to open the issue here since that's the proper way.

**Comment by exectails** [comment]
It's G1, back then bears weren't in, of course your Giant would refuse to have one!

Yea, it's good to have an issue for this, on the old forum we had a research topic about that problem, because I didn't know exactly how they worked. Now I was just about to reopen it, but as I read through my findings from back then, I instantly saw what's going on... past-exec really lacked experience =|

The values `FigureA` and `FigureB` in `ItemInfo` act as a short for the hair item, it's set to the "beard_id", that can be found in the client's item db. We simply have to set that, after adding the beard id to our db.
