### ISSUE TITLE
Party error

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#132]
Upon a player joining a party, this happens http://puu.sh/lNKvA/8165fe4b6b.png

**Comment by QewQew** [comment]
That doesn't look like it has anything to do with parties.

**Comment by RashataanVuul** [comment]
Yeah, I don't know. that happened though

**Comment by exectails** [comment]
*Upon* someone joining a party, you got those two errors? And that's reproducible? o.o

**Comment by RashataanVuul** [comment]
Yes, it is. I set a party max of 2 people. my friend joins and then both of our game crashes and I get that error

**Comment by exectails** [comment]
Okay, that makes more sense, your games "crash" (at least one client tried to notify the server about the disconnect), the connection is lost, and that's where the errors come from. Now the question is, why do the clients disconnect, and why is there a DisconnectInform packet that has different values o.o

**Comment by exectails** [comment]
(\*studies screen shot* I haven't added resurrection yet...? o.o Huh.)

For starters I added a new error message for incorrect packet types, so we get to see the packet that caused the error, but I don't get that error. I can still kind of confirm the problem, my clients freeze when I try to join the party.

**Comment by exectails** [comment]
Looks like there's a problem with the party position, a creature that joins a 2 member party gets position 200 assigned, which shouldn't actually happen... why don't we throw there...

I'd say the problem is this line:
`for (int i = 1; i < this.MaxSize; i++)`
the last available slot isn't checked. I'll confirm that, if nobody else does, when I'm back in a few minutes.

**Comment by exectails** [comment]
Quick fix, should be working now.
