### ISSUE TITLE
Melee Knockdown

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#141]
A full "Melee Combo" usually produces a KnockDown and calls the AiEvent OnKnockDown.

Currently the combo only produces a visual shove (shove animation) without calling the OnKnockDown.
It should be a visual KnockDown(animation) AND call OnKnockDown.

And a visual shove (animation) should also call the OnKnockDown.

**Comment by exectails** [comment]
I think a shove counts as a blow though, doesn't it?

**Comment by Sairii** [comment]
Shove counts as hit but not knockdown in the AI.

**Comment by exectails** [comment]
We really have to agree on some terms here, I'm not sure what you're saying xD"

Shove/Knock back: Sliding back on the ground, without flying.
Blow/Knock down: Flying back, to the ground. Can also happen on the spot in certain cases.
And there is no "visual" anything, it's either a knock back or a knock down.

So, a shove does not trigger "blowhit", right? I guess that would make sense now that I think about it xD" It's not a blow after all.

The problem with melee attacks is that I originally thought that you always get shoved, and only blown on crits. That' how Aura works right. So that's not a problem with the event, but with normal attacks not blowing.

The problem with Smash #140 is that we check for a specific TargetOption, KnockDown, which Smash doesn't use, it uses a different one that we have to check for as well. All other skills work as intended though, right?

**Comment by Sairii** [comment]
Now I am totally confused.

Shove = Knockback : OK
Blowhit = Blow = KnockDown : OK

With visual I meant the animation.
Right now the combofinish produces the animation of a shove. Without actually being a shove OR a KnockDown.

A Shove DOES produce a Blow/KnockDown in terms of AI. (Animation of a shove and still calls KnockDown event)

A critical can(?) produce a KnockDown instead of a Shove.

I didn't check all the skills on aura, it was something that happend.

I will update my other posts to get rid of some of the confusion.

**Comment by exectails** [comment]
If it *looks* like a shove it should *be* a shove, if it looks like a blow it should be a blow. A smash is a blow, because you're sent flying, our shove on a normal attack should be a shove because you're not flying. The problem here is not that a visual one, we simply don't sent anyone flying after a normal attack combo. That's something I haven't gotten around to change yet. And we forgot to create an issue for it I think...

So, *officially*, if you shove a monster, with IB for example on the third hit, does that trigger the blowhit event in the AIs?

**Comment by Sairii** [comment]
>So, officially, if you shove a monster, with IB for example on the third hit, does that trigger the blowhit event in the AIs? Or does it trigger the normal hit event?

>The 3rd hit of icebolt (visual shove/animation) does count as KnockDown in the AI.

Yes 3rd IB hit triggers the blowhit event in the AIs.

**Comment by exectails** [comment]
Alright^^ I committed two fixes that should take care of Smash and Combat Mastery knock down already, but if a shove triggers the blowhit event as well the check can be simplified, to look for any kind of knock.
