### ISSUE TITLE
Defense balance reset

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#142]
I also discovered something else about defense, and that's balance resetting. If I've knocked down a monster and it starts charging defense, I will be able to break it and land additional strikes. I have managed to 8-hit some mobs with dual bastard swords because of them charging defense on agro. I have saved a video sequence of it somewhere I believe if you need some footage.

The case seems to be that whenever a mob charges defense, I will be able to land two extra basic attacks, regardless of the current balance. If the mob is at 0 balance and charges defense, it appears that it will go into a negative balance status so I am able to 8-hit like I mentioned earlier.

**Comment by exectails** [comment]
The actual cause of this is probably that the stun is only set if the target didn't have Defense loaded, but the CM handler currently considers Defense loaded even if it's still loading. As a result you don't get a knockback stun and you can hit some more.

**Comment by exectails** [comment]
I'm thinking about two changes, first, I'm gonna check if the hit was defended, instead of checking the target's active skill id. The other one changing the TargetAction's skill id to only be set to the active skill if the skill is actually ready (loaded), as that makes much more sense.

However, I'm not sure if that second change reflects official behavior. Could someone try to hit a monster *while* it's loading Defense, logging the hit with Pale, to see what the target action's skill id is in that case?

**Comment by exectails** [comment]
Never mind the first change, the second one does exactly what we need, and it also fixes a general mistake in how we set the target action's skill id.
