### ISSUE TITLE
AI Circle stuttering

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#181]
As I was literally filming every step of succubus' movement, I noticed some things.

            Do(Wait(3000, 5000));
			Do(Circle(100, 3000, 3000, true, true));
            Do(Wait(3000, 5000));
			Do(Circle(100, 3000, 3000, false, true));

These are very close Circles around the player and are stuttering on aura. The movement is not smooth.

On official succubus makes a perfect circle.

**Comment by exectails** [comment]
Mhm, I've noticed this on several occasions as well, but always managed to forget about it again. Yay for issues!

Regarding the problem, I assume it's caused by the way Circle currently works. It keeps calculating points to walk to on a circular path, but it doesn't start walking to the next point until it has reached the previous one. Since the AI has a "heartbeat" of 250ms, there can be up to 250ms between the AI reaching one point and it deciding to walk to the next, which causes said stuttering.

The solution seems simple, the AI shouldn't calculate the exact position to walk to, but a position further away. It would then change course once reaching the point on the circle, and since it's still moving, trying to reach the far away spot, there would be no stuttering.
