### ISSUE TITLE
AI Hate on Battlestance. Research needed

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#184]
This one is wierd and might need more research.

In the succubus AI, she never aggroes unless you are in Battlestance.

On official:
Succubus in her alert rotation might attack you to "test" you. Of course you go into Battlestance from being attacked. -> disabled battlestance right away so she doesnt attack
Then a while later she aggroes you.

There are 2 things that could have made this happen:
1. even a second in Battlestance will trigger her aggro after the delay
~~2. her own attack makes her go into aggro (which I think happens at direwolves and gbears alot)~~

**Comment by Sairii** [comment]
Yes, you only need to activate Battlestance for a short time and the countdown starts.

**Comment by DeleteIT** [comment]
>Succubus in her alert rotation might attack you to "test" you.
Combat mode makes her urge to kill rise.

That AI makes zero sense, as an AI.
Either she slaps you, to see if you'll try and attack her, or she only attacks when you switch to combat mode.
*Both* of those makes the entire thing utterly bizarre.

But, perfectly the norm for official, I suppose =/

**Comment by exectails** [comment]
Does attacking from Alert work on Aura? I don't think I've ever tested that.

>Yes, you only need to activate Battlestance for a short time and the countdown starts.

So, she attacks you, notices that you've gone into battle stance, and attacks you shortly after because of it?

Her provoking you into attacking makes sense and is kinda funny, and her attacking you because of you being in battle stance makes sense as well. What irritates me is that her battle stance hate gets triggered by attacking you, because the client automatically switches to battle mode... honestly, this seems like an official bug.

*She* is provoking *you*, and you don't have control over your battle stance in that instance, so if she still attacks you, even though you switched back, that would make her kinda stupid. I can't believe that was their intent when they scripted her.

**Comment by DeleteIT** [comment]
>Does attacking from Alert work on Aura? I don't think I've ever tested that.

It'll have to, Gargoyles and various other things require it.

As for the AI, it should probably just have some sort of `IslappedPlayer`, which when not null and equates to the target currently being checked, forces the hate process to check and see if they're in combat mode when the timer expires.

On that note, how does the AI system work when it comes to multiple people?
Can a mob can be in alert mode against multiple targets on official?

**Comment by exectails** [comment]
>It'll have to, Gargoyles and various other things require it.

I know that AIs use it, my question was if it's *currently working*^^"

>IslappedPlayer, which when not null and equates to the target currently being checked, forces the hate process to check and see if they're in combat mode when the timer expires.

It would work a little differently, but in my previous message I was questioning whether we actually want it to work the official way that doesn't seem right. Right now the Succubus would insta-aggro the player I guess, as we count the time since it went into alert.

>Can a mob can be in alert mode against multiple targets on official?

I doubt that they can alert against multiple targets, but maybe they can be aware of multiple, I don't know. It's not possible on Aura atm.

**Comment by DeleteIT** [comment]
Isn't being aware of targets being in alert mode?

**Comment by exectails** [comment]
In Aura the AI is constantly checking for potential targets in the area, if it finds one, it becomes "aware" of that one target, and after a few seconds without the target leaving, it switches into alert. That "additional" state is kinda needed, because we have to count the seconds until alert is started. I don't know if officials do the same, or if they can "be aware" of multiple targets.

**Comment by Sairii** [comment]
I case you do not have the answer yet...
TL:DR

No it doesn't work on aura.
They are still in alert after attacking you.

**Comment by exectails** [comment]
Of course they're still in Alert after attacking, why would they switch? o.o My question was whether the attacking part works. Afterwards they should switch if they hate battle mode though.

**Comment by Sairii** [comment]
Oh... ye my bad xD
No it works perfectly.
They attack in alert mode.

**Comment by exectails** [comment]
Okay, that's good to know.

Now, about my question how this should work. Back when I added the dungeon reward chests I found several mistakes in their drop lists, where wrong items were dropped. It was clear that they were c&p mistakes, so I fixed them. Aura now actually has different dungeon drops than officials, because we have the drops the original devs *intended*. I see this issue in a similar light.

I can't imagine that they intended for a monster to switch into Aggro by attacking you. It makes no sense to me, and it feels like it's an unwanted side-effect of the client automatically switching to battle mode. It's actually be possible that the auto-switch was added later in development, and they didn't notice it, or didn't care enough to fix it.

So what should Aura do? Behave like officials? Change it, based on the assumption that this isn't what they had in mind?

The battle stance aggro actually seems problematic in general. On officials there's a delay for the aggro, and it's slightly random. If I walk up to a monster and go into battle mode, that should provoke it, so it aggroes me, that makes sense. Waiting a moment and attacking then is okay as well. But if you switch back into normal mode, it will still attack? That's illogical.

While I generally advocate for emulating Mabi 1:1, I highly doubt anyone will ever depend on a monster going into Aggro after exactly 1000~2000ms after switching to battle mode, because that's how it is on officials. That's something the vast majority probably doesn't pay any attention to, just like nobody has ever wondered why they don't get Black Spider Scrolls from Fiodh reward chests.

**Comment by Sairii** [comment]
well... cant we have a option?
I really don't mind either way so why not giving them both options?

**Comment by exectails** [comment]
True, not a bad idea.

**Comment by exectails** [comment]
Battle stance hating is weird. One time a wolf aggroes instantly when you go into battle mode, next time it circles you for *several* seconds before it does anything. I have a hard time believing that's randomness, are we missing something?

**Comment by DeleteIT** [comment]
I assume a lot of that is the mob server being just terrible at its job, since I've seen a lot of that.
IMO, the official mob server isn't very good at processing events, which makes things like this really quite awkward.

In any case, just randomise it a little, since that will make it feel more dynamic/alive.

**Comment by exectails** [comment]
Closing as the discussion is over. AI weirdness was partially solved in #202, aggro behavior might be added as an option at some point.
