### ISSUE TITLE
[Inventory] Control-Click

### ISSUE THREAD

**Issue by ImaBrokeDude** [aura-project/aura#200]
If an items being swapped is larger than the available space in an inv, the item is lost.

Seems to mainly happen if doing so from a style slot.

It was confirmed through another user (causing me to make this) I am now also in the process of doing my own test to confirm, please stand by.

**Comment by exectails** [comment]
Does this mean you can equip items via Ctrl+Click?

**Comment by QewQew** [comment]
Yes, you can.

**Comment by DeleteIT** [comment]
On the subject of equipping, you automatically equip items you pick up, provided you don't have something in that slot.
That is the *ONLY* criteria for not equipping, even if you're using a skill, or otherwise unable to equip something.
(Unless someone has a situation where the server actually won't allow it?)

**Comment by exectails** [comment]
@DeleteIT That should be an issue in itself, but you're right, it's still missing, and I've actually thought about that, I think it might not be limited to picking up, but *getting* stuff in general.

On topic: \*sigh\* When Ctrl+Click-equipping, the clients sends a move request for the clicked item, to the appropriate equip slot. Right now Aura simply tosses the colliding item (the one that was equipped) into the source pocket, assuming that it was the cursor.

```csharp
// Toss it in, it should be the cursor.
if (collidingItem != null)
	_pockets[source].Add(collidingItem);
```

If there's no space, the Add fails, but everything else continues, or rather, is already done.

Can someone tell me the official behavior? What happens if there's not enough space for the swapped item? Does the move get canceled? Or maybe the item goes into the temp inv? Should the colliding item even go into the source pocket, or into general free space?

**Comment by ImaBrokeDude** [comment]
The move will get cancelled normally.It would then display a bottom notice "There is no room in your inventory."

**Comment by exectails** [comment]
> Should the colliding item even go into the source pocket, or into general free space?

**Comment by ImaBrokeDude** [comment]
OH!! Sorry missed that, it goes into any available free space.

**Comment by exectails** [comment]
Alright, thanks for the info.

**Comment by exectails** [comment]
Since disappearing items are kind of problematic, I've hot-fixed this for now, though I'm not exactly happy with the solution. I can't think of a better one at this moment though, 

I'm now explicitly checking if the move is from the inventory to an equip pocket, and whether there already is an item in said pocket. If so, I check if there's enough space in one of the main inventory pockets, to take the item. If not, I cancel the move.

When the time comes to actually move the colliding item, I check the source pocket first, if it was the cursor, otherwise I go through the main inventory pockets until I find one the item fits into. Thinking about it... I could've saved the spacious pocket in the beginning, so I don't have to do it twice >_>

Anyway, If someone can think of a better way to do it, I'm open to suggestions.
