### ISSUE TITLE
unable to enter Morva Aisle

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#210]
I get a feeling this has something to do with the new player collision detection that was added from #176 because I can't enter Morva Aisle from Bangor anymore. It keeps sending me back and flipping my camera angle around.

**Comment by exectails** [comment]
You're right, looks like there's an invisible prop. It's probably the fence, that prevented people from going there in early gens. The prop is in the region data, but apparently it's not supposed to be used. Since I can't see any indicator in the client files for *why not*, I guess I'll remove it explicitly.

![ula_bangor](https://cloud.githubusercontent.com/assets/5593920/12355431/ddbb4924-bb9c-11e5-9801-e87d9a93bfda.png)

**Comment by exectails** [comment]
Found something in the client's prop db for that fence (41277): `feature="-401"`
I guess that means this prop is only loaded below G4S1.

**Comment by exectails** [comment]
Partially related: They do even more in the prop db... the fence that blocks the entrance to the Dugald housing area is opened/closed based on a feature.
`25219: setpropstate(housing:enable, state:open);setpropstate(housing:disable, state:close);`

**Comment by exectails** [comment]
And now that this is fixed, I should actually add that prop, to block the way =P
