### ISSUE TITLE
No stamina consumption when attacking props

### ISSUE THREAD

**Issue by gcscaglia** [aura-project/aura#251]
Attacking props (trees, bushes, poles, etc) doesn't reduces stamina. In original, they consume stamina in the same way a combat attack does.

Tested both with weapons and bare-hands.

Searched for a similar issue but couldn't find any. #125 Is the closer I've got, seems that applying the same stamina calculation for props would do. I'll send a patch If I manage to fix it.

**Comment by gcscaglia** [comment]
I've managed to implement stamina consumption on hitting props in ``Networking.Handlers.Props``, but I have a few questions about how it should be done.

1. How to calculate the actual usage? For single wield and bare hands It's simple, but I'm not sure about dual wield. On ``CombatMastery`` each hit is calculated separately, and so is stamina consumption. When hitting props despite the two hit animation there is only a single ``HitProp``, ``HitPropR`` pair being sent/received.
    * Should we only use the first weapon usage?
    * Should we sum both usages?
    * Another value unrelated to the weapon(s)?

2. The delay sent to the player on ``HitPropR`` is hard coded on ``Networking.Handlers.Props`` as ``1000``, but while logging packets from the original for the tests I've noticed it is ``1000`` for single wield and ``2000`` for dual wield. Should we change it as well?

3. On a side note, checks like whether the player is dual wielding, stamina consumption per hit and similar values are being calculated directly in ``CombatMastery``. We may need that info elsewhere. Shouldn't those be implemented as properties of the ``Creature`` class? If there is no other reason to keep they at ``CombatMastery`` I can refactor those away. Should I?

**Comment by exectails** [comment]
>How to calculate the actual usage?

I just tested it on NA.
* 1 Gladius: 2 Stamina
* 1 Broadsword: 2 Stamina
* Both together: 4 Stamina

So I guess the two should be summed up.

Btw, while testing this I noticed another thing that costs stamina, *swapping weapon sets* o,o" But *only* the "hunger stamina", the brown part of the bar. Weird.

>Should we change it as well?

Absolutely.

>Should I?

Well, they're in Combat Mastery because they weren't needed anywhere else, but yes, putting those in Creature makes sense if we need the information elsewhere. I guess  `IsDualWielding` could be a simple property, but the method to get the stamina usage would need optional parameters, so you can get the usage for a specific item, or for the main weapon, or for whatever the creature is holding?

**Comment by gcscaglia** [comment]
Ok, noted for summing weapons stamina usage, stun and ``IsDualWielding``.

I should be done with testing it by today, but since I'm a subversion guy it should take a while before I figure out how to send a pull request; Expect it sometime before the weekend.

As for the stamina usage method, I was thinking two properties, ``RigthHandStaminaUsage`` and ``LeftHandStaminaUsage`` would do. The right one would check for ``null`` on it and fall back to ``Creature.BareHandStaminaUsage`` automatically, while the Left one would return ``0`` if not dual wielding. I've only proposed to change it because having to ``weapon != null ? weapon.Data.StaminaUsage : Creature.BareHandStaminaUsage`` every time felt like a ``NullReferenceException`` waiting to happen.

**Comment by exectails** [comment]
Hm... yea, I guess that could work.
