### ISSUE TITLE
Account doesn't contain character

### ISSUE THREAD

**Issue by poshwosh** [aura-project/aura#257]
I have updated Aura recently and I have an encountered an error which occurs when attempting to login into a character. 

To the client, it's a simple "Server cannot be reached.".

The server however, logs a login attempt from a null account ID and believes the attempted login is impossible as the character doesn't belong to the null account.

Log:
> [Error] - Problem while loading character '4503599627370498'.
[Exception] - System.FormatException: String was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at Aura.Channel.Database.ChannelDb.LoadVars(String accountId, Int64 creatureId) in c:\User\Poshwosh\Desktop\aura-master\src\ChannelServer\Database\ChannelDb.cs:line 1291
   at Aura.Channel.Database.ChannelDb.GetCharacter[TCreature](Account account, Int64 entityId, String table) in c:\Users\Poshwosh\Desktop\aura-master\src\ChannelServer\Database\ChannelDb.cs:line 305
   at Aura.Channel.Database.ChannelDb.GetAccount(String accountId) in c:\Users\Poshwosh\Desktop\aura-master\src\ChannelServer\Database\ChannelDb.cs:line 99
[Warning] - Client 'xx.xxx.xx.xxx:51149' : Account <NULL> (Controlling <NULL>) just committed a Severe offense. Incident report: GetCharacterOrPetSafe: Account doesn't contain character 0x10000000000002
[Info] - Killed connection from 'xx.xxx.xx.xxx:51149'.

This issue only occurs to characters. Pets are unaffected by it.

After multiple attempts, I have figured out it is related to my account name. 
Changing my account name from "zikkun" to almost anything, solved it, so attempt to login into an account with the same name to replicate it.

**Comment by exectails** [comment]
Do you actually get the exception again if you change your name back...? That would be weird, the error has nothing to do with names. You never had this problem before updating? Can you tell me what language your system is using?

**Technicalities**

The problem comes from an invalid DateTime string in the scripting variable table. Not too long ago I changed Aura to set the application's default culture to one from the conf files, this way we would get strings formatted the way the user wants them to look like.

Unfortunately we were serializing DateTime scripting variables with the installed culture, and not invariant, which means we couldn't just parse them. My hot-fix was to catch the FormatException, and parse the date with the installed culture, as that's what it should've been serialized with, before the update.

What's happening here now is that we get a FormatException in the catch, with the installed culture parsing.

**Comment by poshwosh** [comment]
Yes I do. I changed it back to "zikkun" and it occurred once more.

I have been updating frequently under the same database since 2014 and it only happened now.

Language is set to English. Format and language for non-unicode program is set to English (United Kingdom), not sure if any of them matters.

Unfortunately I don't have any ways to to test this. Have you tried an account with that name?

**Comment by exectails** [comment]
I've actually realized why changing the name worked just now, we use the name as the id for the variable table, if you change your account name, none of the variables are associated with the account anymore and hence aren't loaded. If they aren't loaded, they can't cause an error.

Unfortunately I don't know what exactly might've happened here. It should be near to impossible to get this error, unless you have an old database, with existing data, and your computer is not set to US English. But even then, I thought I caught the problem. I assume it's something about UK English and the date format being slightly different, but I can't be sure.

The simplest solution would be to delete the date variables from the database. To do that, run the following MySQL query:
```
DELETE FROM `vars` WHERE `type` = "dt" AND `accountId` = "zikkun" ;
```

**Comment by exectails** [comment]
Maybe we should delete variables that fail to be parsed by both the new and the installed culture, so this can't happen anymore. It should be a *very* rare corner case, and even if it did happen, nothing too important should get lost, unless someone had some custom script that saved dates via scripting variables.
