### ISSUE TITLE
Freeze after boss in Fiodh

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#266]
I did a quick normal run in Fiodh and was unable to move after the boss fight. I am not sure what triggered this, so I'll let you decide by watching this and reading the attachment

https://www.youtube.com/watch?v=peCNZvHroxg
[ChannelServer.txt](https://github.com/aura-project/aura/files/256402/ChannelServer.txt)

**Comment by exectails** [comment]
Hm... any chance you didn't enter that dungeon alone?

**Comment by Pegwald** [comment]
I entered it with someone, but he froze and got logged out during the run.

**Comment by exectails** [comment]
Alright, in that case I know what the problem is. I always assumed this would eventually become a problem, but never got to looking into it =|

When a client disconnects, its Account variable is set to null. However, this variable is used in methods called from the dungeon finish methods, which causes this null reference exception if the player disconnected, as we go through the list of creatures that were present when the dungeon was created, the "party".

We have to revise who we give stuff to in the finish method. Ideally we won't even store the Creature objects anymore, but their entity ids, creating the list on the fly when needed. The little overhead of looking up max. 8 creatures shouldn't cause any problems, and we'll be able to control exactly who gets put into this group that receives treasure keys at the end of the dungeon.

**Comment by exectails** [comment]
No wonder nobody answers if I forget to ask my question... Can someone tell how the official treasure chest key distribution works? Who gets one? Those who created the dungeon and are still in it?  Everybody who's there? Maybe the ones who were in the boss room? And what if I leave the dungeon and then come back in, will I still get a key?

**Comment by QewQew** [comment]
Everyone on the last floor that belonged to the creating party. Leaving and re-entering will grant a key given that you part of the creating party.

**Comment by DeleteIT** [comment]
A key is given as long as:

- You were part of the group that originally opened the dungeon, leaving the party/being kicked/disconnecting and returning/etc makes no difference, you just need to be one of the people who opened the dungeon.

- You're in the dungeon when the boss is killed.

Additionally, the key is given to you no matter what floor you're on, and cannot be taken down floors, which is a hilarious oversight.

**Comment by exectails** [comment]
>Everyone on the last floor that belonged to the creating party

>the key is given to you no matter what floor you're on

@QewQew @DeleteIT Is the second one correct?

**Comment by DeleteIT** [comment]
I said it because I personally have experience with that, hence the "hilarious oversight" comment.

**Comment by exectails** [comment]
I didn't doubt that, but it might've changed, especially after the recent dungeon revamp. (Wait... do we even have that on NA already?)

**Comment by DeleteIT** [comment]
They let it go for more than 10 years, I kind of doubt they bothered to fix it, even if they were poking around in the code already.

**Comment by QewQew** [comment]
As far as I can remember, you only get the keys if you're on the same floor. I've tried keeping alts at the beginning of a dungeon while playing my main and I wouldn't get a key on the alts at the end.

**Comment by xCryptic** [comment]
Looks like this will have to be tested. I swear I remember going afk with people doing a dungeon and I still got a key.

**Comment by exectails** [comment]
The wiki states
>All original partymates who were present in the dungeon when the Boss Room is initially opened will receive a reward chest at the end.
- Keys to the rewards chest are tradeable but disappear once you leave the dungeon.
- These keys cannot be brought between floors.

It's 3 against 1 now I guess^^ I'll do it like that. Should we ever test it, or should someone proof it's the other way, we can easily fix it.

**Comment by DeleteIT** [comment]
Ah yes, I forgot that you had to be in the dungeon when the room opened to get a chest, but you'd still get a key if you were there when the boss finally died.

Also, you can get the key out of the dungeon with the Dorren's method, I've seen them hanging out outside the dungeons over the years.
They don't seem to disappear either, but that's possibly because people kept picking it up, and resetting the countdown.

**Comment by exectails** [comment]
I don't think keys have a countdown, or a *very* long one, to prevent them from disappearing, making it impossible to open doors/chests.

So if you get a key if the boss dies, but you only get a chest if you were there when the door opened, can there be less chests than keys?

**Comment by DeleteIT** [comment]
>So if you get a key if the boss dies, but you only get a chest if you were there when the door opened, can there be less chests than keys?

Exactly.

**Comment by exectails** [comment]
I think that's an official bug. They call their getter twice, from two different methods. Since they create the chests on opening the door and give the keys on kill, this discrepancy may happen. I've left it the way we had it before for now, doing everything on kill, since there's no reason for there to be more treasures anyway.

I've changed the way the dungeon scripts get the creatures, as such this issue shouldn't occur anymore. I've quickly tested it, but it would be great if guys could give it a try some time, @Pegwald.
