### ISSUE TITLE
Lucky finish bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#275]
I just got a lucky finish, but I was disappointed when I didn't get any gold. Now I'm sad.

**Comment by QewQew** [comment]
What monster did you kill? Does that monster drop gold in the first place?

**Comment by Pegwald** [comment]
I killed a kobold bandit. I am quite certain that they drop gold.

**Comment by exectails** [comment]
Did you modify the gold drop rate on your server?

**Comment by Pegwald** [comment]
Yep, I doubled them because we never really got lucky finishes at all ^^ ''

**Comment by exectails** [comment]
The notice won't appear unless the calculated gold drop amount is higher than 0 and a lucky finish bonus is applied. I can't find anything wrong with the code atm.

**Comment by exectails** [comment]
I've looked over it again, it should be completely impossible to get a Lucky Finish notice with no gold dropping, because the notice code isn't even touched when no gold is dropped. It only shows it while multiplying the amount dropped.

That is unless there was an error, but it's been over a month, I don't suppose you remember or still have the logs?^^"

**Comment by Pegwald** [comment]
Oh that's right. I haven't had this bug since then, so let's just hope it never shows up again ^^
If it does, I'll simply just come back to this issue with the log.

**Comment by exectails** [comment]
Alright, in that case I'll close this for now, we can re-open it when it does happen again.
