### ISSUE TITLE
Missing upgrade effects

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#276]
I upgraded a gathering knife with "Hilt Polishing" (Increase shearing speed (-0.25 secs)
Increased repair cost (×1.7)) twice, but I'm not shearing any faster and the repair cost is still the same.

**Comment by xCryptic** [comment]
It probably has to do with the upgrade itself, not the NPC that upgraded it.

All NPCs pretty much have the same upgrade code (just the text is different). What they repair is controlled by the repairs db.

**Comment by exectails** [comment]
CollectionSpeed and CollectionBonus are among the upgrade effects that don't work yet, as I've never gotten any packet logs for them.

From the source:
```csharp
// TODO:
// - CollectionSpeed
// - CollectionBonus
// - SplashRadius
// - ManaBurn
// - LancePiercing
// - MaxBullets
// - Artisan
```

Some have been ignored for now, because G1. I was sure I added the repair cost increase though... I'll label this with backlog, as it's a missing feature due to a lack of packets,

**Comment by Pegwald** [comment]
I see Stewart has some upgrades available for wands - Do those work? I haven't gotten enough proficiency on a wand yet to try it.

**Comment by xCryptic** [comment]
All upgrades should be applied successfully by all Tir and Dunbarton NPCs. You can see from the list above exec posted to see if the upgrade will work.

You can also edit the proficiency in the database.

**Comment by Pegwald** [comment]
I see. Let's hope I can manage to do this without breaking anything ^^ ''

**Comment by Pegwald** [comment]
Doesn't look like Stewart's upgrades work either. I checked both Chain casting and mana reduction, but neither of those work or display anything.

**Comment by exectails** [comment]
It seems like some upgrade effects aren't actually applied yet... Chain Casting and Mana Reduction are two of them, although they should be displayed on the item, at least now that I've fixed Chain Casting not getting added to the item.

(How did we forget to add so many things...?)

**Comment by exectails** [comment]
I need some data and intel on some of the remaining upgrades, I'd appreciate if someone could help me out with this, as I'd have to prof and upgrade the items myself otherwise, when some of you probably already have them.

**CollectionSpeed, CollectionBonus, SplashRadius**
For those three I need a packet log of an item with them. Just drop the item and log how you pick it up. What I need is the ItemNew packet.

**ManaBurn**
Of this one I need a log as well, however, there's another problem. The upgrade effect called `ManaBurn` in Aura is called `manaburn_revised` in the client files. Another upgrade effect, `ManaUse`, is called `manause_revised`. Going by the Wiki, both of those do the same thing. As an example, take the upgrades for an [Ice Wand](http://wiki.mabinogiworld.com/view/Ice_Wand#Upgrades).

"Lassar's Ice Elemental Resonance Enhancement" reduces Mana Consumption by 4%, "Heulfryn's Ice Elemental Control Enhancement" reduces Mana Consumption by 3%. Both effects have the same name on the Wiki, but are in fact two different ones going by the files. Lassar's uses ManaUse with a value of 4, while Heulfryn's uses ManaBurn with a value of 6.

This pattern of a second Mana Consumption effect that does the same according to the Wiki, but has a different upgrade effect in the files, with twice the value the Wiki lists (e.g. 6 instead of 3 for the above) can be seen in other upgrade lists as well, like the Lightning Wand ones.

What I need to know is if there's any functional difference between those two. ManaUse seems straight forward, but what's ManaBurn?

What I associate with ManaBurn is the Mana you lose when you unequip a magic weapon. Is that what this does? Does it reduce the amount of Mana you lose in that case, and not on casting?

**Comment by exectails** [comment]
I guess we got everything for G1 now =)
http://aura-project.org/forum/topic/115-item-upgrades/#comment-1694

**Comment by exectails** [comment]
Woops. For one, ManaBurn is still missing, and two, I missed some upgrades =< Namely:
- SplashDamage (which I already have, thanks, DennouNeko)
- ImmuneMelee
- ImmuneRanged
- ImmuneMagic

The immune upgrades are the passive defenses for shields.

**Comment by exectails** [comment]
ToDo:
- [ ] MagicDefense
- [ ] MagicProtection
- [ ] MagicDamage
- [ ] CastingSpeed
- [ ] CollectionBonus
- [ ] CollectionSpeed
