### ISSUE TITLE
Magic bolts feels too inconsistent

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#285]
I have a friend complaining about how inconsistent the firebolt is and I can't help but agree on this case. I noticed him charge 5 firebolts and deal 25 dmg at rank A (,I have it recorded). He told me about he also managed to deal only 1 damage with 3 charges of firebolt on white spiderlings, but I haven't seen this myself yet. He had about 75 int when we tested this.
Even though I have 80% balance, casting any bolt feels very inconsistent for me too, so I am making this issue in hope for there being a solution to this problem.

**Comment by exectails** [comment]
You're saying you have 80% balance, did you calculate that yourself? To the best of my knowledge the magic balance has always been hidden. We're using the formula from the Wiki, which is `[(Int - 10) / 4] + 30`. This means if you have say 100 int you have a balance of 52.5%, which we then apply to the magic damage.

Hm... the application could be a problem. The way we apply the balance is that we create a range between `balance - diff to 100` and `balance + diff to 100`.
```csharp
// Randomization, balance+-(100-balance), eg 80 = 60~100
```
I see that this might be a problem if your balance is below or near 50%, because then you hit between 0% and 100%. You could certainly call that inconsistent. But it seems to me like the logic would still be sound... 50% balance equals you hitting 50% of the max damage on average. Though I don't know if that's the correct way to look at it.

**Comment by exectails** [comment]
We might need some research into what the actual range is. How much can you hit over and under your displayed balance?

**Comment by Pegwald** [comment]
I thought magic used normal balance, but I will try to calculate the magical balance then. I can also ask my mage friend for help since he is the one who actually discovered this issue.

**Comment by Pegwald** [comment]
my friend invested a lot of hard work and effort on this issue, here's a link to the document he created regarding this. (File format was not supported so I couldn't upload it.)

https://www.dropbox.com/s/mrgm50fnzlaesqc/Firebolt%20Consistence%20test.rtf?dl=0

**Comment by exectails** [comment]
So these are the numbers from Aura. Mhm. Like he discovered as well, it gets more consistent as you gain int, as that will increase the balance and decrease the randomization range.

Has anyone ever payed attention to this? How *exactly* affects balance the damage? Can you hit max damage if you have only 10% balance? Is the balance maybe the minimum, and you hit somewhere between balance% and 100%? Or maybe the range is static, like +-20%?

**Comment by Pegwald** [comment]
I do believe the higher balance you have, the more reliable output of damage you have. I have 80% with almost any weapon, and my numbers are very stable. I never deal minimum damage, I think. Except for when I use magic. That's not reliable at all for me.
I have never had 10% balance, so I really don't know how the mechanic works for that. The only thing I know is that 80% balance feels like 100%, I feel I only do max damage with swords and crossbow.

**Comment by exectails** [comment]
I've played around with the numbers today and realized our entire balance calculation seemed off. I've changed it slightly and updated the magic balance calculation, so it works more like the ones for melee and ranged. I also found a bug in the damage calculation, which was probably the cause of this entire issue.

Give these changes a try, I'd say it *feels* more accurate now, and the math should work as well.

**Comment by exectails** [comment]
In case anybody is curious what I changed about the balance:

I already described what we did before, we took the average balance and then calculated a random number between that and the difference to 100. However, we capped the min and max at 0 and 100.
```
max(0, balance - diff) ~ min(100, balance + diff)
```
This screwed with the range, because if you had say 40% balance, you would get a range between 0 and 100, for an average of 50%. Same for everything < 50%. What I did now was remove those caps and make the range +- 100, capping the random value at the end.
```
(balance - 100) ~ (balance + 100)
clamp(0, 80, balance)
```
This way you get the correct average in the first step, which is then capped at the correct values, resulting in a better distributed probability.

After I came up with this, I noticed the Wiki apparently had been updated since I last worked on balances, and described the same idea now.

**Comment by Pegwald** [comment]
amazing, I will check it out tomorrow ^^

**Comment by Pegwald** [comment]
I looked up some things regarding the magic bolts. Now it looks like that when lightning bolts crit, it doesn't actually add the critical damage, it just deals normal damage.
Firebolt has become insane too if you crit, but I can't see anything wrong with the math. It's just insane to watch 5 charged firebolts deal 3k damage on crit. (r1 + 600 INT). I'm not complaining, though ^^''
Ice bolt is working just like normal, I suppose.

**Comment by Pegwald** [comment]
*edit: now I am complaining #295

**Comment by exectails** [comment]
We'd have to ask a mage if 3k is a lot for a fully charged R1 Firebolt with 600 Int, but it doesn't seem all that insane to me. Doing 2k Smashes wasn't too hard on EU iirc, why shouldn't a 3k Firebolt be possible, which has to be cast first?
