### ISSUE TITLE
Sword of Elsinore treated like a regular sword 

### ISSUE THREAD

**Issue by ash-l** [aura-project/aura#289]
I know this is probably too early to say this, but I noticed you could pick up a sword of Elsinore without having rosemary glove assuming if you spawned a sword of Elsinore and dropped it onto the ground!  This should not happen because you could not drop a sword of Elsinore onto the ground in official server. Even somehow by triggering certain condition (Unknown), client will pop out a warning message you cannot drop this item onto the ground, but by attempting multiple times you still able to actually throw the sword onto the ground. 

P.S. The sword model on the ground looks really cool :D.

**Comment by exectails** [comment]
Yea, it is a little early, I'm not worrying about items you can't get legitimately yet. As such I'll put this on the back burner.

**Comment by exectails** [comment]
Can you tell me the message that appears when you try to drop it on officials?

**Comment by exectails** [comment]
I've realized the Sword of Elsinore has the tag `/not_dropable/`, which is used by many undroppable items. It's fair to assume they all use the same message, through a check for this tag, which I have now added.

The other issue, the Sword being "operationable" without the gloves is a G13 issue that we can handle some other time. By the looks of it, the sword you can find is not a prop, but the actual item which simply appears standing up when dropped. Since you can only equip it when you have equipped the gloves, you can't pick it up without them.

This requires another check on equipping, potentially switching, and picking up, for the `/hamlets_sword/` tag. We also need the message that appears when you try to touch the sword without the gloves, and we need to know what happens if you switch to the sword without the gloves. Or maybe you can't even unequip them? In that case we need that message as well.

All relatively simple, it just needs research.

**Comment by ash-l** [comment]
Unfortunately I no longer own a rosemary glove in official server, I sold the glove after I quit. 
I do know that after you pick up the sword, there will be a special event triggered, playing a small cut scene showing you unplug the sword(lol).  And the sword stays in your inventory, only can put to owner's bank, you can't drop it or trade it nor transfer that to a pet.  If you attempt to equip the sword without the glove, I remember the message is exactly same as attempting to "pick up" the sword in Avon without glove.  I remember if you equip the sword and switch the weapon set, then un-equip the glove,  switching back will not active the sword, it will appear like a weapon out of durability, and not equipped.

**Comment by xCryptic** [comment]
This is when you try to equip the sword without the rosemary gloves
![](http://i.imgur.com/9UqDAIM.png)
If you try to take the gloves off while the sword is equipped, it will just take the sword and put it in your inventory w/o a message.
If the sword is in your secondary slot (not in your hand) and you remove the gloves, the sword won't be put in your inventory until you switch to your secondary slot.

**Comment by exectails** [comment]
Since all information were supplied, I've decided to already add this, since it's relatively simple and might help if there are other items that have such restrictions.
