### ISSUE TITLE
Weaving gloves has no effect

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#293]
I have a suspicion that the silk/fabric weaving gloves does not apply a higher success-rate for making a certain type of product. Normally you would get a higher success-rate for making (for example) common silk/fabric if you equipped common silk/fabric weaving gloves, but I have a feeling that this does not happen since I get all the other products of silk/fabric and rarely the one I want.

I did some testing with the GM, attempting to make as much **fine** silk and fabric as possible out of 100 thin threads and 100 thick threads. I equipped only **fine** silk/fabric weaving gloves for this test.

Silk Results (total of 20):

- 8 cheap silk
- 3 common 
- **2 fine**
- 7 finest

Fabric results (total of 20):

- 5 cheap fabric
- 6 common fabric
- **7 fine fabric**
- 2 finest fabric

I was a little surprised about how different the results between silk and fabric were, but I still have a feeling that there's something that doesn't feel quite right. I also discovered that the fine fabric weaving gloves didn't decrease in durability, despite the fact that I had to buy two pairs of fine silk weaving gloves in order to complete this testing. _Two birds with one stone_ ^^

**Comment by exectails** [comment]
You're right, those gloves are basically not handled at all, because I didn't realize they had any effect, didn't even remember the fabric ones existed o,o" The wiki doesn't seem to mention them on the skill's page either. Are you certain that they affect the chance for their respective quality (fine, finest, etc)?

The fact that I didn't realize the fabric gloves existed is also the reason they don't lose durability. Silk gloves are *required*, so durability is removed, but for fabric they're optional, so they're dismissed because no tool is specified for them in the db.

**Comment by Pegwald** [comment]
I am very certain they do, it just wouldn't make any sense if you could purchase any tier without them having any effect at all. It's in the description that they increase the chance of making a certain type of silk/fabric, depending on which you look at ^^
http://wiki.mabinogiworld.com/view/Fine_Silk_Weaving_Gloves_(Type_1)

I never did tailoring or weaving in NA, so I was unaware that fabric gloves were optional... huh. Now I know :)
