### ISSUE TITLE
Crossbow bug - Magnum shot disables run/move

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#296]
When wielding a crossbow, you should be able to run with skills, but this doesn't happen with magnum shot. You get stuck in one place once you load the skill.

I can't believe I've missed this...

**Comment by xCryptic** [comment]
Straight from Wiki:

![](http://i.imgur.com/grOe8jF.png)

**Comment by exectails** [comment]
I guess this was an Archery Renovation change, as up until December 2015 it said

![](http://puu.sh/piw3h/a78d916490.png)

Actually a weird change, from not being able to move at all to running o.o

**Comment by Pegwald** [comment]
oh, I read it from http://wiki.mabinogiworld.com/view/Category:Crossbows were it isn't even mentioned. Sorry pals, this wiki fooled me so many times now x-x''

**Comment by exectails** [comment]
All good, @Pegwald, you were right. @xCryptic just gave a reference so I don't have to ask how you know that, and I noted how it was different just a few months ago, explaining why it was implemented the way it was^^

The reason you were stuck was that the server prevented the Run command from being processed, because running was locked when you prepared Magnum. If you had used Shift, you would've been able to walk. The fix was to only lock running for bows and not lock anything for Crossbows.
