### ISSUE TITLE
Smash and Final Hit

### ISSUE THREAD

**Issue by tokinodesu** [aura-project/aura#315]
**Smash:**
Issue: The counter window to Smash by Normal Attack is too short.
Scenario: Sometimes I can't counter enemy's Smash by using Normal Attack, we need to react earlier to increase the chance.

**Final Hit:**
Issue: Skill is able to cancelled by knock back (Counter or Windmill)
Scenario: Checked G19 patch note, the Final Hit has updated and cannot cancel by knock back.

**Comment by xCryptic** [comment]
The final hit length isn't an issue if you're a GM (using the gm title).

**Comment by tokinodesu** [comment]
You mean the unlimited time of Final Hit is cause by account level is greater than 0?

**Comment by xCryptic** [comment]
I can't remember if it's the auth level or the gm title. I'm thinking it's the gm title though.

**Comment by tokinodesu** [comment]
Oh, my friend tried using GM title or non-GM title, still got unlimited time, no idea is it need to relogin.
But thanks Cryptic information.

By the way, I just amend the issue of Final Hit.

**Comment by exectails** [comment]
The Smash issue is part of #7. The server currently doesn't control who hits first, as a result the first attack command to come in will be the one that's being processed. This will be fixed in the near future.

Final Hit is not being canceled by knock back anymore...? Ugh... thanks for the reminder, though do keep in mind that the server is currently designed to be G1-like. A G19 feature not being implemented is not considered a bug, but simply something we didn't need yet.

I'll put this on the backlog, adding a custom canceler to Final Hit isn't much of a problem, and when we already have the skill we can just as well add it completely.

**Comment by tokinodesu** [comment]
You're welcome :)

Here is the patch notes (G19: Section Renovation):
http://wiki.mabinogiworld.com/view/Patches#Generation_19:_The_Divine_Knights

**Comment by xeroplz** [comment]
Another issue with Final Hit is that it knocks down enemies that can't be knocked down. The code was changed to be Knockdown all the time, but the check was never changed from Knockback.

**Comment by exectails** [comment]
@xeroplz This should fix it.
