### ISSUE TITLE
Mana deflector reduction

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#330]
I'm not sure about this, but I have a suspicion that the damage reduction from mana deflector (level 2 and up) is ignored. My mage friend is able to deal consistent damage on Gorgons with his firebolts, and sometimes he can even kill one in a single blow (critical hit). The other two passive shields seem to be working like normal, heavy stander and natural shield.

**Comment by exectails** [comment]
Gorgons have R6 Mana Deflector (the Wiki's Level 1-3 categorization is made up, these are normal skills with normal ranks), which gives them 0% damage reduction and 100% delay reduction. This means your observation is accurate, but expected behavior. R6 Mana Deflector won't reduce the damage.

Going by Wiki logic I'd say at least normal Gorgons actually don't have Level 2, but Level 1, which makes it an error in their Gorgon data.

**Comment by boilerplate5** [comment]
Holy moly, the L1-2-3 is made up? That is some good info right there!

**Comment by exectails** [comment]
@boilerplate5 I can't tell whether that was sarcastic or not xD

**Comment by Pegwald** [comment]
The damn wiki gets me every time... xD
