### ISSUE TITLE
Repair cost bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#331]
_This time I was the one who managed to scam Nerys by repairing my fully upgraded gathering knife._

I had 0 gold on me when I tried fully repairing my gathering knife at Nerys, but she needed 2900g for the repair. "Fine" I said and ran over to the bank, withdrawing (accidentally) 2823g instead of 2900. I returned to Nerys and she completed the repair without failure... and without subtracting any gold at all from me.

**Comment by exectails** [comment]
She took no gold *whatsoever*? You shouldn't even be able to get past the cost check .__. What did you repair?

**Comment by Pegwald** [comment]
> fully upgraded gathering knife

It's upgraded like this:
Double Collection (40%)
Increased shearing speed (-1.00 sec)
Repair Cost ×83.5

**Comment by exectails** [comment]
Do you think it's possible that *some* gold *was* removed? We're talking about just a few coins here, since a non-upgraded Gathering Knife only costs 7g per point at Nerys.

What I did find is that apparently we're not setting the increased repair price anywhere... this is so weird, I was 99.9% sure I had added that, but I can't find it anywhere o~o That would explain why you "bypassed" the cost check though, because it checked for the normal, non-upgraded price.

**Comment by Pegwald** [comment]
Ah, I didn't see that before now. I had originally 2858g and had 2823 after the repair. I didn't notice this before you asked ^^''
