### ISSUE TITLE
Create a Shop Command

### ISSUE THREAD

**Issue by xCryptic** [aura-project/aura#34]
Title pretty much says it all. An example would be

`>shop shopname`

so if you have the shop `bubbles` in the shops folder or w/e, you would type

`>shop bubbles`

**Comment by exectails** [comment]
Sounds good to me, and we have to investigate the functionality sooner or later anyway, for the remote shop items.

**Comment by exectails** [comment]
This was a little more tricky than I anticipated. When  you send just the open shop packet, the client does nothing. It actually wants the response to the remote open shop packet first, that you get when using a remote shop coupon.

The next problem is that it uses some NPC packets, to close it again for example, that the server didn't react well to, since there was no actual NPC session going on.

But the `>openshop` command is working now.
