### ISSUE TITLE
PTJ are all taken

### ISSUE THREAD

**Issue by tokinodesu** [aura-project/aura#341]
I tried Endelyon's PTJ with only 1 user online in the server.
But she always said the jobs are all taken....

**Comment by exectails** [comment]
She will say that if there are no more jobs for today (Endelyon's PTJ can be done 20 times per in-game day), or when you already did her job today. Does one of those apply by any chance?

**Comment by tokinodesu** [comment]
I didn't take or finish any jobs at Tir

**Comment by tokinodesu** [comment]
Ok. I figured out the issue, but I also find out a strange issue on PTJ available slot.
Here is my testing in my own server (just 1 user online):

Day0: Server restarted
Day1: PTJs are all taken.
Day2: Checked available slot=20 before start the PTJ
Day3: Checked available slot=19 before start the PTJ
Day4: Checked available slot=18 before start the PTJ
Day4: Server restarted
Day5: (repeated symptom as same as Day1 )

**Comment by exectails** [comment]
I'll test it later, though nothing like that has happened to me yet, weird. Could some else give this a try as well?

**Comment by exectails** [comment]
I found 1 bug, which was that the remaining PTJs weren't resetted, meaning you had 20 per server restart, and if you did the PTJ 20 times, you wouldn't get any more. What I'm not clear on is why you start with 0 after a server restart, that I can't reproduce at all.

Could you try the latest version, where I fixed the reset, and check if the problem is still there?

**Comment by tokinodesu** [comment]
Confirmed the problem was fixed lol (including server restart issue).
Thank you exec :)

**Comment by exectails** [comment]
Thank *you* for the report and assistance =)
