### ISSUE TITLE
Unable to specify additional conditions on Gather or Collect quest objectives

### ISSUE THREAD

**Issue by valdeza** [aura-project/aura#343]
Current implementations ([QuestObjectiveGather](https://github.com/aura-project/aura/blob/159840e538a74866639f83d793cff4c63064fd23/src/ChannelServer/World/Quests/Objectives.cs#L225), [QuestObjectiveCollect](https://github.com/aura-project/aura/blob/159840e538a74866639f83d793cff4c63064fd23/src/ChannelServer/World/Quests/Objectives.cs#L74)) only allow scripts to specify an item and an amount. Some future quest objectives will specify additional conditions on the requested item, such as cooking food of at least a certain quality or fishing for carp of at least a certain size.

dependent: pending link to unimplemented npc:caitin.ptj: carp fishing

**Comment by valdeza** [comment]
### Proposal_
**Edit: This proposal has a problem. See "Possibly affected files" below.**

Provide the following method overloads:
```csharp
// aura/src/ChannelServer/Scripting/Scripts/QuestScript.cs
protected QuestObjective QuestScript.Collect(int itemId, int amount, Func<Item, bool> conditions);
protected QuestObjective QuestScript.Gather(int itemId, int amount, Func<Item, bool> conditions);
```

#### Possibly affected files_
* _aura/src/ChannelServer/World/Quests/Objectives.cs_  
Will need an overloaded constructor to use `conditions`. MetaData will probably need to be set with the required conditions (unconfirmed, can't choose which PTJ I get).
* _aura/src/ChannelServer/Scripting/Scripts/QuestScript.cs_  
Methods attending to `ObjectiveType.Gather` and `ObjectiveType.Collect` will need to be updated to query item metadata.  
**Problem: Only item IDs are used throughout this code file. Need to somehow access metadata.**

#### Usage example_
```csharp
AddObjective("ptj", L("Deliver a 10cm+ Brifne Carp"), 0, 0, 0, 
	Collect(MISSINGNO227, 1, (item) => {return item.MetaData1.GetFloat("SIZE") > 10.0f;}));
// "SIZE" might not be the key name, but is used for illustrative purposes
```

#### Considerations_
Those wishing to make custom quests should expect a little bit more coding complexity in exchange for more complex quest conditions.  
Or should this be abstracted away somehow so that the scripter does not need to know lambda expressions and to call `Item.MetaData1.Get<T>()`?

**Comment by exectails** [comment]
Your idea of proving overloads for lambdas is pretty interesting, this could be done for rewards as well, so scripters can create custom objectives and rewards without core changes.

However, as you noted yourself, this doesn't quite work the way you're trying to use it. With the current system there's no way to carry the item from the point where it was gathered to where it needs to be checked by the quest objective, but that's actually not needed. Unlike rewards, objectives don't have any code themselves, they are checked based on their ObjectiveType in QuestScript, and the items are removed via the quest scripts.

The lambda you're proposing would be used [here](https://github.com/aura-project/aura/blob/master/src/ChannelServer/Scripting/Scripts/QuestScript.cs#L713). It would be passed to the inventory to count the items that match it. However, this won't be necessary for Caitin's PTJs, because she doesn't actually use Collect or Gather, it's two new objectives, *fishing something* and *delivering an item with a certain size*. These two objectives will most likely be their [own type](https://github.com/aura-project/aura/blob/master/src/ChannelServer/Network/Sending/Helpers/QuestHelper.cs#L129) and should be handled separately.

I haven't actually encountered those two myself, so the type and its metadata still has to be logged, and the objectives have to be added.

**Comment by exectails** [comment]
@valdeza Have you seen the fishing quest on NA lately? I was online all day, checked all channels almost every in-game day, but haven't seen it yet o~o

**Comment by valdeza** [comment]
I have not; it's just that it's listed as one of her PTJs [on mabiwiki](http://wiki.mabinogiworld.com/view/Caitin#Part-time_Jobs).

Really, before deciding to help with dialogue collecting, I only worked for the churches. >_>

**Comment by exectails** [comment]
Maybe that PTJ doesn't even exist anymore. It would be weird for them to remove it, but if we can't get it...?

**Comment by valdeza** [comment]
Well, assuming there's a pool of 8 basic PTJs from Caitin to randomly pick from, we have varying levels of confidence that the fishing PTJ is not offered:
80% confidence - 13 attempts (6 real hours)
90% confidence - 18 attempts (8.5 real hours)
95% confidence - 23 attempts (11.5 real hours)
99% confidence - 35 attempts (17.5 real hours)
`> 1-{ConfidenceLevel} = (7/8)^{n}`

Whenever I do my next round of dialogue recording, I'll stop by Caitin's and see if she offers it.

**Comment by exectails** [comment]
I've checked her again a few times today and I still have't see it. You know, I really believe they removed it. Right when I first read that quest I thought to myself "They expect you to fish something specific, with a certain size, under time pressure?"

Since fishing is basically luck based, in its entirety, both the time it takes until *something* bites, and what bites, and the size if it, you could easily fail the PTJ. That was probably deemed unfair at some point, and the Wiki only still lists it because it existed at some point.

**Comment by valdeza** [comment]
I agree it's unfair and should not be requested of players, but it was common for people to pre-gather the quest materials they can before it is asked of them (church part-timers).

**Comment by exectails** [comment]
Yes, but in this case the quest *required* you to fish it fresh, you couldn't get it upfront.

**Comment by valdeza** [comment]
Oh that's _mean_. Since it's the server that decides what PTJ is offered for the day, removing them from rotation is as simple as commenting out the fishing QuestIDs, yes?

**Comment by exectails** [comment]
Yep.

**Comment by exectails** [comment]
I'm going to close this, as we have to assume the PTJ doesn't exist anymore, so we currently aren't able to get the objectives logged.

The lamba suggestion is interesting, but currently impossible to implement. The objectives would ideally need a little more control, but they aren't designed that way, instead they're currently supposed to use pre-defined types, which are handled by QuestScript, without  much logic in their classes.
