### ISSUE TITLE
NpcScript GiveItem & GivePoint

### ISSUE THREAD

**Issue by tokinodesu** [aura-project/aura#345]
Here is a part of my script:
`GiveItem(2006,2);          // Gold Pouch * 2`
`GiveGold(100000);          // Gold * 100K`
`GiveItem(63029,10);            // Camp Kit * 10`
`GiveItem(63000,20);            // Phoenix feather * 20`
`GiveItem(63044,20);            // Party Phoenix feather * 20`
`GiveItem(51005,100);       // Red 300 Potion * 100`
`GiveItem(51010,100);       // Blue 300 Potion * 100`
`GiveItem(51015,100);       // Yellow 300 Potion * 100`

However, I just got the following in my bag:
Gold Pouch \* 1
Gold \* 100K
Camp Kit \* 5
Phoenix feather \* 20
Party Phoenix feather \* 10
Red 300 Potion \* 20
Blue 300 Potion \* 20
Yellow 300 Potion \* 20

In additional, I checked src/ChannelServer/Scripting/Scripts/NpcScript.cs, seems no function to add Points to player, would it possible to implement that? Thanks.

**Comment by exectails** [comment]
Regarding your points question, you can access and modify those via `Player.Points`.
```csharp
if (Player.Points < 30)
  // Not enough points

Player.Points += 20; // Add 20 points

Player.Points -= 10; // Remove 10 points
```
See the custom [points shop](https://github.com/aura-project/aura/blob/master/system/scripts/custom/points_shop.cs) for an example.

Now, the result of your code is technically not a bug. GiveItem allows you to give one item, with a specific amount, capped at its max stack value. As a result, "giving two" Gold Pouches will give you only one Pouch, but with an amount of 2, which in this case would be 2 Gold.

Similarly "giving 100" potions will add one stack of 20, because only *one* item is added, that item having a max stack of 20.

There is a method that does what you're looking for, but there's currently no shortcut to it from NpcScript, it's `Player.Inventory.InsertStacks(itemId, amount);`
Though that wouldn't work as you'd expect it to in all cases either, because it adds *stacks*, and a Gold Pouch stacks way more than 2, so you get the same result^^"

I'll mark this as a discussion, since we're essentially talking about the default behavior of GiveItem. Quite obviously it doesn't behave like some might expect. I can certainly see why you'd think your first call above would add 2 pouches.

Question to everybody: Is the current behavior of GiveItem counter intuitive?

**Comment by valdeza** [comment]
I also would have expected two gold pouches on the script. I'm not able to look at the code right now, so I don't know if it's more efficient to expose `InsertStacks()` or loop through `GiveItem()` if one were to deal with values too large:
```
If param2 > {max stack size}
	numStacks = param2 / {max stack size}
	numRemain = param2 % {max stack size}
	For 1 to numStacks
		GiveItem(param1, numStacks);
	If numRemain != 0
		GiveItem(param1, numRemain);
```

Otherwise, if a scripter really wanted multiple stacks, it becomes their responsibility to loop `GiveItem()` an appropriate number of times.

**Comment by exectails** [comment]
If 99% of the users expect a GiveItem method to add as many items as specified though, we should change the default behavior. InsertStacks actually does something different than GiveItem. While GiveItem adds one stack to the inventory, InsertStacks tries to insert into existing stacks first.

If you have a 500g stack in your inventory, and you do `GiveItem(2000, 100)`, you'll get a second gold stack, with amount 100. If you do Insert, the 100g with be added to the existing stack, for one stack with amount 600.

**Comment by tokinodesu** [comment]
I suggest GiveItem will add the actual value of the item
And InsertStacks will add the max stack of the item, for example, InsertStacks(45001, 1), will add 100 arrows to the player.

**Comment by xCryptic** [comment]
We could do something like
`GiveItem(id: 43312, stack: 5, amount: 3);`

**Comment by exectails** [comment]
@xCryptic Somehow missed your comment.

Don't you think that might be equally hard to wrap your head around? Does it add 5 stacks with 3 items each? Or maybe 5 stacks that are filled up to 3? It could also be the other way around, an are those inserted into existing stacks first?

Though I suppose the last one would always be expected^^

**Comment by xCryptic** [comment]
Hmm... true. I guess using another function would be less confusing. Here's another idea:
`GiveItem(43312, 3);` gives 3 separate items
`AddToStack(43312, 4);` adds 4 to first stack (to total 5) - if there isn't a stack, either just add 4 in a single stack or add a warning in console
`AddToStacks(43312, 4);` adds 4 to each stack (to total 5) - if there isn't a stack or there's only one stack, add a warning in console

**Comment by exectails** [comment]
Do we even need a "quick access method" that doesn't add to existing stacks though? Off the bat I can't think of a reason why you would want to add a bunch of potions, gold, or other stackable items, without trying to add them to existing stacks first.

**Comment by valdeza** [comment]
Items that expire. Stacking up items with different expiration times will produce a single stack with the expiration time determined by a weighted average of all items that compose the stack. 
Some players might prefer to have one item that expires in 1 hour and another that expires in 1 day rather than two that expires in 12 hours 30 minutes.

Just giving an example. But I don't think that alone warrants a "quick access method".

**Comment by exectails** [comment]
There are stacking items that expire? Huh. But you're right, I don't think such an obscure case, where someone wants to give expiring stack items via an NPC, while leaving players the choice to merge them, really warrants its own method. Especially since you can still do it, if you work directly with the creature's inventory.

**Comment by YaibaToKen** [comment]
Apologies for not noticing there was an issue for this already. I do agree with @valdeza and your's last comment @exectails

**Comment by exectails** [comment]
@YaibaToKen Totally missed your question here, what exactly is your problem, you want to *insert* an *Item*? For that you'd use `creature.Inventory.Insert`. I'll fix this issue now though, and afterwards the helper methods will all behave like we discussed, adding to stacks first.
