### ISSUE TITLE
Failed Malcom PTJ

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#390]
I'm so happy we finally have this PTJ ^^
Too bad senpai Malcom won't notice my great work. I made two very nice Mongo's traveller suits, but when I reported my work, he disapproved.

**Comment by Pegwald** [comment]
https://youtu.be/qX6ubziq4T0

**Comment by Pegwald** [comment]
Might be because I am able to report much earlier than I am supposed to. I did a delivery quest and when I reported (brought back a flower pot), he accepted it and didn't reward me anything. I still have the quest.
https://gyazo.com/38a2350acd447a3ff6c4aab686646408

**Comment by valdeza** [comment]
> I made two very nice Mongo's traveller suits, but when I reported my work, he disapproved.

Oh, shoot. I forgot to report that. Thanks for bring it up.  
I believe the problem might be the second "Collect" objective not being immediately checked for after completing the first "Create" objective. For some reason, you have to somehow update your inventory to complete the Collect objective (typically dropping something or splitting a stack).

And.. currently investigating your second issue. Will edit this when I find something.

**Comment by Pegwald** [comment]
> second "Collect" objective not being immediately checked for after completing the first "Create" objective.

^^

**Comment by valdeza** [comment]
>  I did a delivery quest and when I reported (brought back a flower pot), he accepted it and didn't reward me anything.

Just realised you said you were reporting early. The only way to be rewarded for PTJs is to return after report time (9a when delivering clothes to Bebhinn for Malcolm). Before then, for the most part he will otherwise chat with you normally. Without exiting and re-entering the NPC chat session, one can attempt to resubmit their work through the Part-Time Jobs keyword.

I doubt official has him say anything special when giving him Bebhinn's flowerpot too early, but the only way to be certain is to do just that and log it, I suppose.

**Comment by exectails** [comment]
@valdeza The question with the flower pot is whether he is supposed to accept it before the report time. You're checking for the quests being active, but not whether it's the report time, resulting in him taking the pot but doing nothing else.
https://github.com/aura-project/aura/blob/master/system/scripts/quests/ptj/general_malcolm.cs#L108

**Comment by exectails** [comment]
About the other issue, if you used the official objective types, I'd say the problem is #230. You have 2x create and then 2x collect, it wouldn't make sense for the second objective to just be done after the first is done, the second one is presumably supposed to count up as you finish the first one.

Though you're right of course, it should still work on Aura. Once the collect objective becomes active, it should be checked, that's the bug we have to fix for now.
