### ISSUE TITLE
No in-game error message when using mill with item in hand

### ISSUE THREAD

**Issue by Natje0** [aura-project/aura#397]
When you try to use the mill with items in your hands (It won't let you do that) there's no in-game notification at all, it merely doesn't start or do anything.
Error code given when trying to do so;
`[Warning] - ProductionSkill.Complete: Creature '0010000000000004' tried to produce without empty hands.`

**Comment by exectails** [comment]
What happened here is not that we missed to give the appropriate message, but that you ran into sanity checks, basically an anti-cheat prevention, that shouldn't even be triggered under normal circumstances, because the client normally prevents incorrect use of tools like the mill.

In this case we were interpreting the client's data incorrectly, trying to prevent something that should be allowed. I'll fix it.
