### ISSUE TITLE
Messenger

### ISSUE THREAD

**Issue by exectails** [aura-project/aura#4]
The messenger server, responsible for friend list, notes, etc.

- [x] Login
- [x] Group management
- [x] Friend list
- [x] Chat
- [x] Multi-chat
- [x] Options
- [x] Notes
- [x] Blocking
- [x] Blacklist

**Comment by xCryptic** [comment]
This should be worked on next :+1:

**Comment by Xcelled** [comment]
:+1: and also Blade wants this as well.

[2015/9/6 7:47:44 PM] Nicholas LaPointe: Do you think Friend's List and shit will be working any time? [soon]

**Comment by exectails** [comment]
Well, I *vaguely* remember *someone* working on this, but since he never made a clean *pull request*...^^ Maybe I will do it, that would actually be a kinda fun thing left in the backlog.

**Comment by Xcelled** [comment]
Yeah, @epicmiro !

**Comment by epicmiro** [comment]
-stare

**Comment by epicmiro** [comment]
I never made the new pr because i didnt have messaging 100% (maybe 1v1 messaging was 100% last time i worked on it)

**Comment by exectails** [comment]
@epicmiro There is no reason why you have to finish an entire system by yourself, you could've always pushed the finished handlers/senders, enums, etc. Nobody expects you to write an entire server 100% correct from A-Z by yourself.

**Comment by epicmiro** [comment]
@exectails Well i once pull requested, and i remember no-one even bothering to look at it... I could send my messenger server which basically has everything working except multichat (you also forgot blacklisting and group management in your checklist btw), but my repo on github has been deleted since i saw that the project discontinued. It might help to see what i did for each handler and such to avoid problems you might get (For example, for chat, each player has a session id which is for that single player only, when the chat is closed, this session id will expire and any new incoming chat from that same person will use a new session id. The session id's are different for all participants in the same chat.)

**Comment by exectails** [comment]
> also forgot blacklisting and group management in your checklist btw

That's part of the friend list.

>Well i once pull requested, and i remember no-one even bothering to look at it

I remember two pull requests, one was horrible and the other one was just one giant commit, where we told you we would've preferred a better commit history, but the reason we didn't look at it in detail was that it still was the same as before, just in one bit commit... wasn't it?

**Comment by exectails** [comment]
Notes are done, yay~
