### ISSUE TITLE
Proper Prop Hit Range

### ISSUE THREAD

**Issue by QewQew** [aura-project/aura#407]
Currently, the range for hitting props is fixed at 1500. This needs to be corrected somehow.

**Comment by exectails** [comment]
The 1500 were set as a security check, just to make sure nobody hits a prop from across the map, under the assumption that the client would go close enough by itself. Was that assumption incorrect?

**Comment by QewQew** [comment]
1500 is pretty much across the map, too. /shrugs

**Comment by exectails** [comment]
The check is a little generous, I picked that randomly, just to have something, though it's nowhere close to across the map (see below) =P  I'll change it to 500, that's still more than enough.

![unbenannt-1](https://cloud.githubusercontent.com/assets/5593920/18343837/4d5c1484-75b5-11e6-8bcf-fe1b5053fe96.jpg)

**Comment by exectails** [comment]
And just as I did that change I remembered there probably was a reason for it... there are very large props, and we check the distance to the center of the prop. I guess we'll see if 500 is actually enough. Or maybe the check has to be changed a little altogether. TouchProp had the same problem =/

**Comment by QewQew** [comment]
Well, if it means anything, being able to hit a prop should work something like hitting a monster; the range scales with the size of the prop and the size of the character.

**Comment by exectails** [comment]
Yea, it should^^

**Comment by QewQew** [comment]
Did you RE the client to get the formula for combat range? Why not do the same for props?

**Comment by exectails** [comment]
At some point we should probably do that, but I'm not too concerned about such a minor security check at the moment.

**Comment by QewQew** [comment]
Also, being able to touch props without a proper distance check would allow you to bypass seal stones and such.

**Comment by exectails** [comment]
It's certainly something we can and should flesh out at some point, but in my opinion it's not a major issue that needs immediate attention.

*Theoretically*, if there's a touchable prop *right behind* the seal stone, you could touch it if you're packet or memory editing, but we're talking about a minor security check here. 1500 wasn't a lot, as you could see above. Just enough to touch something behind a seal stone. I can't think of much abuse potential here.

**Comment by QewQew** [comment]
>Just enough to touch something behind a seal stone.

Wouldn't that mean touching portals that are right behind seal stones (e.g. going to Dunbarton even if it's still sealed off)?

**Comment by exectails** [comment]
We'd have to measure that, but usually the portals aren't *right behind* the stones I think, there are still a few units between them. ... now I'm curious, let's take a look.

Between your position in front of the stone and the portal in Dugald Aisle are 1000 units, so you could indeed mod your way past that stone, with the 1200 unit check we have for touching props at the moment. A quick test shows that touching a portal moves you to about 400-500 units away from it, so we should probably use something like 750 for the security check. A collision check could also be an option.

Right now I'm more worried about props being untouchable than modders though. If there's a shapeless prop that's bigger than our check radius, you wouldn't be able to touch it.

It would be interesting to see how the client does it, because from the data we have I don't see a straight forward way to determine how close you can get. Not all props have a shape defined, there is no range or size in the data, so all you're left with is a range to the center.
