### ISSUE TITLE
Incorrect repair costs

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#411]
I have a pickaxe with increased repaircost, but when I'm repairing it through Edern, the displayed cost is 815g per point. I actually paid 1386g per repair.

I'm not sure if other npc has the same issue, but I think we've had similar issues before, like with Nerys.

Edit: I can confirm Elen also has the same issue, displaying 54g cost per point when it's actaully 91g.

**Comment by exectails** [comment]
Same thing with Gathering Knife. Since normal repairing seems fine, I guess it's a problem with the increased repair cost.

The problem with the repair cost display is that the client does that automatically, and the server has to adjust. If the server comes to a different result of what the repair should cost though, it removes a different amount of gold than the client displayed.

I'm sure it was correct when I fixed it last time, so I assume they lowered the repair cost. I'll look into it.
