### ISSUE TITLE
Stewart's PTJ - recieve book on statistics

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#412]
I was very confused when doing this PTJ. The quest info told me to first talk to Austeyn, then the other part of the quest was to recieve the book.

Here's what happened. I talked to Austeyn who didn't give me any quest dialogue, just the "what do you need?" prompt and a selection of various options to do - like normal. I got the book, but according to the quest tab I've only spoken to Austeyn, but not completed the second part: "Recieve book on statistics". I had the book in my inventory, but what did it mean? I went back to Stewart to report the job, but I failed him. I still have the book in my inventory.

What went wrong? Is the quest info incorrect or was I supposed to get "recieve book [  ]" checked?
I wonder if I had to place the book back at the library, something that the quest never explained, but really would make sense.

**Comment by exectails** [comment]
After taking a quick look at the script it seems like Austeyn isn't supposed to say anything special.

You were indeed supposed to complete the objective, if the objective isn't complete, the PTJ will fail. The reason it didn't complete automatically, even though you had the book, was because the talk objective was finished after you got the item.

Since right now we still have the problem that the next objective is not checked automatically when it becomes active, you would've needed to drop the item and pick it back up, for it to get registered.

I took a step at fixing the problem, it should hopefully work now. @valdeza We have to pay attention to this.
