### ISSUE TITLE
Stewart's PTJ - multiple book quest

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#414]
I collected books from Aeria, Walter and Simon to deliver them back to Stewart, but after completing the PTJ, Stewart only took one of the books (that being the one from Simon). The other two remained in my inventory. This guy must be the worst librarian in whole Erinn.

**Comment by valdeza** [comment]
Ah, yes. I did bring that up before ([#230](https://github.com/aura-project/aura/issues/230#issuecomment-244764835)), but there is the problem of modifying CreatureQuests.cs as is potentially causing some sequential order-type quests to remove items twice: once when the quest script removes it over the course of the quest and again when the quest is completed. 

Stewart's PTJs are supposed to be one of those quest types that can be done in any order and we currently have no implementation for it. 

@exectails : Should this be fixed as part of implementing "any order" quest types or should I write in a small hotfix in Stewart's PTJ for the moment? When the player talks to Stewart to complete the quest, I can have it remove the other books depending on quest ID.

**Comment by exectails** [comment]
I dislike looking at this script, it's too complicated for something so simple =/ Wt... what is this o,o `string.Concat("ptjDeliver", i.ToString())` Was `"ptjDeliver" + i` too simple? xD

>Stewart's PTJs are supposed to be one of those quest types that can be done in any order

Doesn't really matter in this case though, does it?

I don't quite understand what the problem is, if the Deliver objective is a problem you could just use Talk and handle everything manually. That's probably better until we have a better handle on the objective management. Don't worry too much about the official objective types, use what works.
