### ISSUE TITLE
G1 quests added in wrong tab

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#420]
https://gyazo.com/42f787f96c507a0cfa09660ab9f948dd

I noticed that the mainstream quests have been added into the wrong quest tab - Basic instead of Advent of the Goddess

**Comment by exectails** [comment]
That's actually expected behavior, based on this feature setting: https://github.com/aura-project/aura/blob/master/system/db/features.txt#L343

Though I see how this might be confusing. I didn't know the client displayed the G1 tab without any tabs in it, just because G1 is currently active when I added that feature. What do you guys say, should the G quests always go to their tabs, despite that setting?

**Comment by exectails** [comment]
+1 for confusing, +1 from a user, I'll do it.
