### ISSUE TITLE
Mimics are not staying open when aoed by windmill etc.

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#435]
How to reproduce: Windmill 2+ mimics
On Aura the mimics that got hit all close again except the one aggroing you.
On Official every mimic stays open (look at dem teeth) without moving. 
They only close 1.: aggroed mimic runs till it loses aggro. Goes back and closes somewhere? Not exactly sure when or how.
2.: If you lose sight of them??

Im not 100% sure on how they actually close again. I also cannot test it right now because I can only play official via VPN right now and I am losing my mind because of lags and disconnects....

**Comment by exectails** [comment]
On Aura, do they still attack you after you killed the one that aggroed you, even though they closed again after being hit?

**Comment by Sairii** [comment]
Actually, no I don`t think they do.

**Comment by exectails** [comment]
It seems like Mimics are open as long as they have a target, aka when they're in alert or in aggro, and close down when it's gone. Since Windmill only causes one monster to aggro, the other Mimics close back down. Now iirc monsters aren't supposed to go into alert when being "passively" hit by Windmill, is this different for Mimics on officials?
