### ISSUE TITLE
Lassar does not teach Magic Mastery when asked about Skills

### ISSUE THREAD

**Issue by valdeza** [aura-project/aura#459]
Reported on Gitter by @lieutenantteddy

**Comment by exectails** [comment]
This is expected behavior in classic G1. You get a quest to learn it after you've completed the beginner quest "Visiting Bangor".
http://wiki.mabinogiworld.com/index.php?title=Magic_Mastery&oldid=51382#Obtaining_the_Skill
https://github.com/aura-project/aura/blob/master/system/scripts/quests/beginner_uladh/200075_magic_mastery_lesson.cs#L18
