### ISSUE TITLE
Players do not recover full hp after being revived after a level up

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#462]
In official if a character levels up while knocked unconscious, they are healed to full health upon being revived (full hp, mp, stam, wound, and hunger). In Aura the character is still revived with low hp and high wound rather than being fully recovered.

**Comment by Sairii** [comment]
Yes that is correctish i think?
But isn't this only the case if a party member used a feather?

**Comment by eotetb** [comment]
I'm actually unsure of how it works for other methods, I should have mentioned it, but I was referring to reviving via feather specifically. After I revived my party member after she had just leveled up, she did not heal after revival.

**Comment by exectails** [comment]
Thanks for the report. My first thought was that this sounds like an official bug, the player bypassing the revive penalty, and this might very well be the case, but it would also make sense to do it explicitly, since otherwise you lose the level up "recovery bonus".

Since I'm not sure which one it is, and since we're emulating, we should add it. We'll probably need a field in temp for it though, to detect the level up once the player is finally revived.
