### ISSUE TITLE
Stuck walking after defense (Classic combat)

### ISSUE THREAD

**Issue by RashataanVuul** [aura-project/aura#472]
So when I disable "CombatSystemRenewal" and "TalentRenovationCloseCombat" to bring back the old classic combat system, I have this one problem that after I successfully use defense by using the skill and blocking an attack, I'm stuck walking and I can only get out of it by relogging. :(

Edit: Further more what I've also noticed that it seems that I cannot counter a smash attack with a normal attack. I don't know if that was only part of the new Combat System Renewal or if that's always been a thing. (This also happens WITH the Combat System Renewal)

Edit 2: Another thing I noticed which I'm not sure if this is normal or not but if I click a spot for my character to run to then activate counter-attack, my character keeps running til' he reaches the spot that I clicked for my character to run to. I THINK it suppose to make your character instantly stand still as soon as you activate counter-attack

**Comment by Sairii** [comment]
>I have this one problem that after I successfully use defense by using the skill and blocking an attack, I'm stuck walking and I can only get out of it by relogging. :(

Yes thats not normal and happens to me aswell.

>to run to then activate counter-attack, my character keeps running til' he reaches the spot that I clicked for my character to run to.

Yes thats also not really normal


>Edit: Further more what I've also noticed that it seems that I cannot counter a smash attack with a normal attack. I don't know if that was only part of the new Combat System Renewal or if that's always been a thing. (This also happens WITH the Combat System Renewal)

Ugh... thats being worked on i think: https://github.com/aura-project/aura/pull/401

**Comment by exectails** [comment]
About counter: https://github.com/aura-project/aura/blob/master/src/ChannelServer/Skills/Combat/Counterattack.cs#L50

We should make that a separate issue if this behavior is incorrect, but I'd like to think that I did test this somehow, otherwise I don't think think I would've stated it as fact.

Now regarding Defense, this sounded very familiar, and I think we've had an issue about not being able to run after canceling it before. The solution was to unlock running twice, for some reason, so I tried that here as well, and it worked.

Unfortunately we have to override client behavior to *simulate* classic combat, since there's no other way to activate it anymore without some serious client-side modding, so I ask you to forgive a few hiccups^^
