### ISSUE TITLE
No herbalism rain bonus

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#479]
Herb patches are supposed to contain more herbs when there is rain (the amount depends on the strength of the rain, up to a max of 5 extra if there is a thunderstorm).

Currently the bonus either doesn't exist, or does not apply to herb patches in Fiodh Dungeon (I have yet to test herbs in fields with rain active). I only received 5 herbs from the patches without any extras during rain.

Edit: there is no bonus in fields either.

**Comment by Pegwald** [comment]
Oh I remember something like that. I believe there's supposed to be up to 8 herbs you can pick out in the fields depending on weather, but I can barely remember this... I think this was a thing at least.

**Comment by exectails** [comment]
Thanks for the report. I will take a look at this.

Quick question, is it a fact that it depends on the rain strength, or is that a Wiki myth? Right now we use a static bonus.

**Comment by exectails** [comment]
I just tested it in east Tir, near Ciar, and I was able to pick 10 Base Herbs during rain, as expected.

The way this system works is that a Base Herb patch for example has a "volume" of 100, and each time you pick a herb it's reduced by 20, but during rain it's only reduced by 10, which allows you to pick twice as much. (You can find these values in the collecting.txt.)

That being said, I don't think I've ever implemented rain inside dungeons... is that a thing? If so, that's the problem, because from the server's POV there is no rain in that region. Can you tell me which region's weather Fiodh is using?

**Comment by eotetb** [comment]
I had picked it in Tir Chonaill. Its possible it wasn't out and I got unlucky with fails. Currently there aren't messages for when gathering props run out of materials or if you fail, so its hard to tell the difference.

**Comment by exectails** [comment]
There is no message when you fail, only if it's empty.

Please give it another try. I've fixed the problem with Fiodh, and picking in fields seems to work as expected for me.

**Comment by eotetb** [comment]
Yeah, it seems I was mistaken then for field herbs. Haven't had a chance to test Fiodh again since the change though. I ended up thinking it was empty after failing multiple times in a row thinking the herb patch was empty; I didn't receive a message from that so I'll assume it wasn't really empty.

**Comment by exectails** [comment]
Alright, I will close this then, since it seems to be working now. Should there be more issues we can reopen it.
