### ISSUE TITLE
Sen Mag Plains?

### ISSUE THREAD

**Issue by ArieJoJo** [aura-project/aura#483]
I can't enter Sen Mag. I'm not sure if this is a bug or not.

**Comment by exectails** [comment]
Hi, thanks for the report. I can imagine why it's not working, and it's an easy fix. However, I was actually just wondering if Sen Mag was part of G1, and after looking it up, it seems like it isn't. I guess I will fix the portals, but also close down Sen Mag, since you're not officially supposed to be able to go there.

You will be able to easily remove that block of course, via a simple feature setting.

**Comment by exectails** [comment]
The portals work now, but to actually get to them, you have to enable the `SenMag` feature first, otherwise 3 bolders block the path to the portal.

**Comment by Cosrnos** [comment]
Sen Mag should have been a G1 Feature just to get to them but the seal stone was locked until G2. I've got a few memories of staying camped out waiting for the stone to break :P

**Comment by exectails** [comment]
@Cosrnos Seal Stone? To my knowledge there is no Sen Mag Seal Stone o.o

**Comment by Cosrnos** [comment]
The seal stone to emain macha

**Comment by exectails** [comment]
So you're saying Sen Mag was open in G1? The wiki says it was added in G2 though o.o
