### ISSUE TITLE
Error in Damage calculation for Skills

### ISSUE THREAD

**Issue by Achrome1** [aura-project/aura#507]
So, I have a bit of an error that hasn't been bugging me too much (Since I have been mostly playing with magic the time being), but I have this small issue with elf melee where the damage would be improperly calculated. For instance, Windmill at rank D for Elves does about 110% melee dmg, however at 20-38 damage vs Coyote (Which, from reading the races.txt, has no base def or protection. Just the 1 point of defense from 10 str), Windmill would rather hit at around 10-15.
I have a video to show this off if needed, Just ignore me being really dumb here and there. XD
This video might not also show it properly, but I also noticed skills were at 50% their usual cooldowns-- At least it let me load them before they were finished in their cooldown. Not quite sure if that's because of the server I was on specifically, but they ensure me they haven't done any tampering with it much at all.
The very odd part is looking in Skills.txt... Nothing appears wrong at all. ._.  Var1 is the damage percentage from observation, but it just doesn't seem to register properly at all. Not to mention Cooldown is at 4.5 as it should yet I've been able to key it off quite sooner, so I'm honestly quite conflicted as to what this means.

**Comment by exectails** [comment]
Thanks for your report.

Since the damage calculation is in no way race dependent, except for the race-specific values coming from the skill data, I would except damage calculations to be off for all races, not only elves. Nobody has report any problems with humans or giants yet though. Is this exclusively an elf problem?

**Comment by Achrome1** [comment]
I haven't gotten around to seeing if there's another elf with the same issue, but I don't really have a lot of info on giants, but as far as I know it SEEMS to be ok for them. I haven't quite gotten anybody to stick around long enough to actually want to run tests with me, so everything's been pretty inconclusive there. As far as I know, I'm the only person with the issue.

**Comment by Sairii** [comment]
Thought the same some time ago.
Did some testing regarding Ranged Attack damage. But after going back and forth between aura and official, the aura damage calc for ranged was pretty much spot on.
Not sure which race i was testing with. Prolly Human.

**Comment by exectails** [comment]
For clarification, when I say "all races", that includes humans. There's no difference in the calculations at all. Only the bonuses that go into it, coming from the skill data, are different for some skills.

**Comment by Achrome1** [comment]
I can show you the video, though I'm not completely sure about your policy on linking in the github, so I'm refraining on it for now, but to be honest I'm not even sure what would be causing it to happen. ._.

**Comment by Pegwald** [comment]
I looked into this and discovered what's wrong. If you equip a shield, the damage will be significantly reduced.

I created an elf to try this out and did 10-12 dmg with normal attacks and did a stable 25 dmg smash with rF smash, rF CM and Eiry as my weapon. I looked back at the sequence Sonata posted earlier and found it odd, but I had a theory that the shield could have been a cause of this problem. I borrowed a shield and tested it and figured the damage now with smash was reduced to 14. Normal attacks worked just fine, pretty much what seems to be the problem here.

**Comment by Achrome1** [comment]
Aaaaaaaah.
Could the server just think I might be "Dual Wielding" In some instance using a shield instead of another sword?

**Comment by Sairii** [comment]
>Is that the feeling you frequently tell me to trust? =P

No my gut feeling is something completely different. Its above reason and numbers.

**Comment by exectails** [comment]
>Could the server just think I might be "Dual Wielding"

That's exactly it. Can't believe I didn't think of that, we had an issue like that before @_@ Thanks, @Pegwald.
