### ISSUE TITLE
CCing without wand

### ISSUE THREAD

**Issue by Achrome1** [aura-project/aura#515]
Accidentally posted this before writing @.@
The long and short of it is, Was testing out a bug I posted earlier and possibly solved by Pegwald to confirm, and I discovered that with my wand in my inactive right hand with my sword being active, I can actually chaincast without using my wand actively
Using a Gladius, and a Ladeca short sword to do this, but when i'm bare handed, doesn't count.

**Comment by killer000** [comment]
So you are like mores?

**Comment by Achrome1** [comment]
In a sense, although the moment I switched weapons back and played with my shield to do more testing, It sorta just stopped happening altogether.
Trying to see if I can recreate whatever instance that caused it to happen, since I don't recall doing anything before or after logging in today or logging off last night.

**Comment by exectails** [comment]
It does *sound* super weird, but luckily the solution wasn't all that complicated^^

For those curious: There are different kinds of upgrade effects, and one kind of upgrade type, which Aura calls "WU upgrade", was applied to all items that were equipped. Now normally, during game-play, you can only actively move items to the main equip slots, and to get to the others you have to switch. Both equipping and unequipping removes upgrades of the items becoming inactive, but when you log in with an item in your secondary slots, the upgrade effects could be activated, because there was no check for it being in a secondary slot. This was now fixed.

Thanks for the report.
