### ISSUE TITLE
Golem cannot sleep when player dead :<

### ISSUE THREAD

**Issue by Sairii** [aura-project/aura#52]
Pretty sure exec knows about this and i know the current way the golem idle is done is not final but...

The poor golem cannot sleep / idle when the player dies to it.
As soon as the player is dead the golem starts to "spasm" jumping up and down from the sleep.
And as soon as the player hits the revive button -> everything is ok again.

Just sayin. Nothing major, just so we don't forget / overlook.

**Comment by exectails** [comment]
Noticed this as well, already forgot about it again. See, issues are good^^

Well, *apparently* we didn't check potential targets for being dead. So when the AI tried to select a target, it used the dead player. But right after doing so, there's a check that puts the AI into Idle, if the currently *selected* target is dead. This would put any AI into an Idle loop, while being near a dead, potential target.

In the case of Golems this was very noticeable, because it would make them go into Rest and stand right back up in a loop.

Before our little hiatus I had planned to work on AIs, I should get back on that soon.
