### ISSUE TITLE
Quest Command

### ISSUE THREAD

**Issue by xCryptic** [aura-project/aura#541]
After writing some quests, I realized we don't have a quest command.

Ideas:
`>quest 123 // Starts the quest`
`>quest 123 1 // Sets the first part of the quest complete`
`>quest 123 all // Sets the entire quest as complete`

**Comment by exectails** [comment]
Personally I haven't had the need to control a specific quest like this yet, because I always want to test all parts of it, but I'm sure there might be a use for it.

**Comment by xCryptic** [comment]
Not even the first example? I've re-done quests to test them multiple times, each time I just removed the info from the database, which got annoying.

**Comment by exectails** [comment]
If I'm testing something over and over I use `>nosave`, I want *nothing* getting saved in that case.

**Comment by eotetb** [comment]
I also use the `>nosave` command when testing quests, but a function to restart quests without having to delete them from the database would be a nice quality of life feature.

**Comment by eotetb** [comment]
When I was using those g13 server files I noticed that official does have a quest gm command to start new quests. I can certainly get by with the `nosave` command, but it would be nice to have a quest command.

**Comment by exectails** [comment]
I've added it, with one minor difference that made more sense to me in our environment. Instead of using a objective number, I made the command use the objective name. It will finish all objectives up to the one specified, so to finish all of them you use the last one. For example: `>quest 202003 talk_deian2`

Since this command will be used mainly for testing while scripting, it seemed more straight forward to me that you would specify the exact objective you want, instead of a number that could easily be wrong, and you counting the objectives.
