### ISSUE TITLE
Composing not possible to do

### ISSUE THREAD

**Issue by killer000** [aura-project/aura#545]
Right when you select a score scroll and click ok none thing happens.

I believe being on skill rank novice causes the issue

**Comment by eotetb** [comment]
I tested this at both rank Novice and rank 1, and the skill worked as it should have.

**Comment by killer000** [comment]
Hmm yeah the compose seems to work on ranks above novice no problem for me.

Ah I think I might have found the problem, I didn't have musical knowledge for the compose so I couldn't compose maybe some kind of message should be showed in the future.

**Comment by eotetb** [comment]
The character that I tested novice compose on did not have musical knowledge at all, so that shouldn't be the problem.

**Comment by YaibaToKen** [comment]
I seem to be having the same problem though, can't rank up my composing skill because I can't compose xD

**Comment by exectails** [comment]
I'm not sure whether this problem was caused by MusicQ, but the reason Composing failed was that the skill handler though you were cheating. Luckily it was an easy fix.

For those interested: The MML is sent as one string, separated with commas. For example: "aaa,bbb,ccc". If you don't send anything in one part, it's empty: "aaa, bbb, ". However, Since every character in those parts contributes to the length of it, including spaces, the above string was split into those three by Aura: "aaa", "bbb", and " ", and since you're not allowed to use part C on rank Novice, the skill handler failed.

**Comment by YaibaToKen** [comment]
Just to let you know that the new update brought a new feature to composing. You get a free score scroll per day that you can claim when composing. Basically, pressing the button free scroll will consume that one instead of prompting you to pick one from your inventory. As far as I've tried, that feature is still not working, though no error messages were shown in the channel server window

**Comment by exectails** [comment]
Well it's not a G1 feature^^

**Comment by YaibaToKen** [comment]
When you use the compose skill, at the bottom of the composing window, it also prompts you if you click the compose button with no score scrolls in your inv. And yeah, it's true it's not G1 :)
