### ISSUE TITLE
Quest items should be destroyable

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#560]
Someone ran Malcolm's ring quest with someone else and killed the spider, but this person managed to obtain the ring again even after completing the quest. Now this item is stuck in this player's inventory.

Shouldn't there be a way to destroy items like this? I know about other people who still has Tarlach's locket in their inventory due to being able to complete their own quest requirements from another person's RP - which brings me to think - Aren't you supposed to be the only one able to complete your own quest if you created the RP? Right now every member who's on the same quest as the dungeon host can complete their own quest requirements without offering their quest items.

After Genesis it was actually possible to do those dungeons solo, but I can remember pre-Genesis were if you were in a party of 3 and everyone were on the same quest, you pretty much had to do the same dungeon 3 times in order for everyone to proceed.

**Comment by eotetb** [comment]
Due to a current glitch, you can get rid of those otherwise non-destructible items by selling them to an npc. Of course that is only a temporary 'fix'.

Honestly, I don't remember how the rp quests worked pre-genesis. But if they weren't changed to be cleared only for the leader, perhaps there could be a check for those rp-items that would destroy them after getting past that part of the generation.

**Comment by exectails** [comment]
I made it finish all party member's quests, because I thought it was kinda stupid that you have to run everything a dozen times. Though that was a questionable decision, as it's not a perfect emulation.

Regarding quest items being destroyable, that depends. If they have the Destroy button, they should be. That doesn't come from the server, it's client sided. If it has the button, but it doesn't work, it's because the server doesn't know it's supposed to be destroyable.
https://github.com/aura-project/aura/blob/31bb2b918ba520c97da5554d264caa5aef481740/src/ChannelServer/Network/Handlers/Items.cs#L339

You're saying people still have Tarlach's Locket, but... that's a dungeon pass, isn't it? So you have to be able to drop it, no? If so, what's the problem with getting rid of it?

**Comment by Pegwald** [comment]
How about creating a feature were every party member in a dungeon/RP will be rewarded quest progress when enabled? When disabled, the host will be the only one getting quest progress, making it a perfect simulation. ^^

The locket can be stored in "me" inventory. Maybe that's why people are still holding on to them like a trophy or whatever.

**Comment by exectails** [comment]
So... if that's not the issue, what is?^^"

>creating a feature

It would be a conf option, because it's not official, but yea, that could be done.

**Comment by exectails** [comment]
Ah... I was wondering "if the killer is supposed to get Malcolm's Ring, but you can't get rid of it without the quest, why is it even possible to get it if you're not the leader?" The answer: That's a solo dungeon, you're not supposed to go in there with a party xD"
