### ISSUE TITLE
Keys not dropping until monster is completely finished.

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#581]
Similar to past issues regarding dungeon room doors opening, while in a party (or playing with a pet) monsters will not drop the key until they are finished. In official monsters are supposed to drop the key upon death instead of upon finish, this is true for treasure chest keys as well. This can also lead to party members getting stuck if someone were to disconnect or if a pet finishes a mob and it becomes unfinishable for any reason.

**Comment by exectails** [comment]
We briefly talked about this in #551, and in combination with #582 it definitely makes sense to drop them... but I really wonder why we went back to kill monsters back then when someone forgot to finish it... maybe they didn't despawn? At least in dungeons?

**Comment by Pegwald** [comment]
Could it happen that the mob who holds the key has some protection from expiring if it haven't been finished yet? Every other mob expires if they don't hold an important items such as a keys or quest items.

It doesn't seem to be wrong that back in EU, we had to run back to pick up a key because someone didn't finish a mob, but I wonder if this was different in NA since I can certainly remember keys dropping anyway - even if the "keyholder" goes into finish status.

**Comment by exectails** [comment]
>some protection from expiring

That might how it was, would make sense.

I think this is something where we can simply use the (maybe) "new" behavior, it makes more sense and people are bound to be confused about this difference between Aura and current officials.

**Comment by exectails** [comment]
Do we know which items this affects? Is it only keys?
