### ISSUE TITLE
Un-synced weather/success rate bonus?

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#586]
I noticed a sudden success rate drop when I was going to make some tough string in Emain. First I had 77% success rate in making tough string (rank 4 weaving + 275 DEX + Monday buff) and it was currently sunny. When it started raining, the success rate suddenly dropped to 74%. I ran over to Dunbarton were it was currently sunny, and the success rate there was even lower - 73%. What's up with that? o-o

**Comment by exectails** [comment]
You're citing the rates the client displayed in the production window, right? In that case I really can't tell what happened there, because what's *displayed* is entirely client sided, we have no control over that. Even the weather is client sided unless we override it.

A few things that come to mind, that should be asked just in case: Were you in a party? Was it midnight and the Monday bonus disappeared? Did you rank Production Mastery or did your Dex stat change?

**Comment by Pegwald** [comment]
Oh I forgot to respond to this.

I was in no party, it was during the night, but it was not during the time tuesday buff overwrote monday, also worth mentioning that I also have Production Mastery r1. My dex did not change.

**Comment by exectails** [comment]
This is definitely weird, but since these displayed chances are client sided we can't really do much about it. Maybe take comfort in knowing that the server probably didn't jump around willy-nilly like that and kept the chance consistent behind the scenes? =P

**Comment by Pegwald** [comment]
> willy-nilly like

probably the best description I've heard in a while xD

**Comment by exectails** [comment]
I'll close this then, since we have no control over it. I assume it was a glitch, because I really can't think of any logical reason why that should've happened.
