### ISSUE TITLE
Attack Animation

### ISSUE THREAD

**Issue by xCryptic** [aura-project/aura#59]
The attack animation won't let you move until after it's finished.

**Comment by exectails** [comment]
Iirc we discussed this issue in length on the old forum and the chat a while ago. I remember that we added a cap to the player stun, which improved the situation. Then, after some new update, the remove stun packet was suddenly sent always, not randomly anymore, which reduced the stun further, and we didn't implement that yet.

The question nobody could ever answer was: how was it in the past? Had the stun always been this short? That would be weird, because I *know* it only happened randomly when I first researched it. Going further back, to old EU packets, we can see that there once wasn't a cap on the player stun, this means that either the client changed somehow, or in the past we had really long stun times.

And the final question is, how *should* it be in Aura *right now*?

**Comment by xCryptic** [comment]
Hmmm.. if it really was random in the past, I guess make it a feature.

**Comment by exectails** [comment]
For reference, the packet I mentioned is 0x7020:
```
Op: 00007020, Id: 0010000000123456

001 [..............12] Byte   : 18
002 [........000005DC] Int    : 1500
```
I think this is a stun "update", which overrides whatever stun was inside the combat action packet. This packet is usually sent shortly after the combat action pack. (The byte is probably the type, allowing an update other things as well.)

Looking through my logs, I only see this packet for normal attacks though, is this short stun time limited to normal attacks?

**Comment by exectails** [comment]
>is this short stun time limited to normal attacks?

Anyone?

**Comment by Raphatlas** [comment]
Kinda, from my memory, the stun was based on the speed of the weapon/skill being used etc, kinda like how it works with monsters. Also, if it helps, the maid, butler, and commerce partners seem to all react to everything the same way a player would've reacted prior to the combat change.

**Comment by exectails** [comment]
Thanks, @Raphatlas. We do base the stun on the weapon speed. This issue is not about the base stun time though, but about it being reduced, so you may move again sooner. Like if you 1HKO monsters with Smash, and you go from monster to monster, without stun reduction you have to wait until the animation is through. That's not exactly how it is on officials right now though, where you're able to kinda "skip" a part of the animation and move along quicker.

**Comment by Raphatlas** [comment]
Ah I see, my bad. Well actually, now that I think about it, the old system isn't limited to just the partners, but just any pet in general. Maybe if you run around playing a pet you own, you'll get the results you're looking for?

**Comment by exectails** [comment]
It won't help with figuring out the answer to my question, but it could tell us if this stun reduction was part of a combat update, which would be useful^^

**Comment by Raphatlas** [comment]
Dang, aw well. By the way, sorry to go somewhat off topic, but how would one go about removing the player stun cap for experimental purposes?

**Comment by exectails** [comment]
@Raphatlas https://github.com/aura-project/aura/blob/master/src/ChannelServer/Skills/CombatAction.cs#L151

Lower the max stun value (milliseconds), then recompile.

**Comment by Raphatlas** [comment]
Oh my goodness that explains everything, knew which files I had to mess with but didn't realize I had to recompile, lol. Tyvm for the replies.
