### ISSUE TITLE
Arrow Revolver Quest gives you a physical scroll

### ISSUE THREAD

**Issue by eotetb** [aura-project/aura#592]
Starting the arrow revolver quest gives you a physical quest scroll instead of placing the quest scroll into the hidden quest inventory. Unless of course this used to be an old feature that was changed, currently though the player should not get a physical quest scroll.

**Comment by exectails** [comment]
That is in fact how it was in the past. People used to give up the quest, while keeping the book around to collect pages, since you wouldn't be able to start more than one advanced skill quest at a time and this quest scroll took up valuable space. When they had completed the book they would get the quest again to drop off the fully enchanted book.
