### ISSUE TITLE
Remote Healer Coupon 

### ISSUE THREAD

**Issue by killer000** [aura-project/aura#594]
Doesn't seem to work, just makes you stuck on the spot until you either logout or restart the client. Guessing you need the packet for it? same with all Remote Coupons?

**Comment by exectails** [comment]
I actually have logs of the remote healer and the weapon shop coupons, they just haven't been implemented yet. If you want to research the remaining coupons though, please feel free to do so and post them on the research section of the forum, in case I missed something.

Since this is a simple case of unimplemented items I'll close the issue, because if we had an issue for everything that hasn't been implemented yet because it's something special or not part of G1 and 2 we'd have hundreds^^

**Comment by killer000** [comment]
Hmm strange I got it from the Treasure Chest Event you setup, in a premium chest no idea if you actually did put a remote healer coupon it in or not. Maybe the Host did?
