### ISSUE TITLE
Exchange bug

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#76]
When you right-click a player and attempt to exchange, both characters will be stuck and unable to move. The players must then force themselves to log out. This has been a very efficient way to troll players other on my private server, but my friends are starting to find it very annoying :P

**Comment by xeroplz** [comment]
That's just because it's not implemented - it's not necessarily broken

**Comment by exectails** [comment]
@xeroplz You're right, it's not a bug, but an issue is completely justified, seeing how it can be exploited.

But I wonder, it locks *both* characters...? That's a little weird. I see how it would lock the one requesting the trade, because there's no response, but the other character should't be affected by that o.o

**Comment by xeroplz** [comment]
I've tried exchange as well. I'm pretty sure the recipient gets locked as well because they are supposed to have data sent to their client from the trader. It'll say "exec wants to trade" or whatever, and I guess that makes it somewhat dependent?

On the other hand, equipment view only affected the viewer because the viewing didn't affect the equipment owner's client at all.

**Comment by exectails** [comment]
That's practically impossible, because the server would have to send something to the other player, which it doesn't, because there is no handling for trading. When person A tries to trade with person B, A gets stuck, because the client never receives a response to the request, but the client is waiting for it. B wouldn't even notice this request, at all, because it never gets notified about the request.

**Comment by QewQew** [comment]
>I've tried exchange as well.

Did both characters get locked?

I can't reproduce this either.

**Comment by xeroplz** [comment]
Hmm... That's really odd then, but yeah both got locked when I used Exchange. However it wasn't very recently but it was on Aura 2.

**Comment by Pegwald** [comment]
I remember discovering it when i tried to exchange with a friend. He suddenly went "Oh I can't move." Then I laughed hard, he logged out, and then I couldn't move. I am not sure if i was unable to move the entire process, but I remember Karma being there for me.

**Comment by exectails** [comment]
But was he unable to move because you tried to trade him, or because he tried to trade you as well? Because, I really don't see how someone would get stuck because someone tries to trade with them. Nothing is sent to them.

**Comment by exectails** [comment]
Regardless of whether this can be used to make others get stuck, can someone get use a log of a trade, so I can create a dummy handler for the moment?

**Comment by exectails** [comment]
I have the packets now, and I've added a dummy handler, so you're at least not stuck anymore after selecting "Exchange".

**Comment by exectails** [comment]
Closing this, since the issue is kinda solved and we have an issue for trading (#112).
