### ISSUE TITLE
Non-displayed additional defense and protection

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#91]
While activating defense or equipping a shield, there's no display of additional defense or protection in character info. Usually you can see an increased amount of current defense and protection when you for example equip a shield, but this does not happen.

**Comment by exectails** [comment]
Mhm. The bonus is applied, but it's not sent to the client. The reason is that equipment currently doesn't actively add the stat bonus, it's queried later, when calculating Defense/Protection, to use it.

We have to change this, adding and removing the stat bonuses on equipping/unequipping. I think there's even a TODO comment for this somewhere in the inventory code =P

**Comment by exectails** [comment]
My explanation was half correct. If we didn't handle it at all, it wouldn't display it for armors and stuff. Said TODO comment does exist, and we are being lazy about it, but what was actually going on, was that the hands were ignored when calculating the Defense and Protection mods.

I want to change the way this works eventually, but I don't want to rip apart the inventory in passing, that wouldn't end well.
