### ISSUE TITLE
Disabled Loom

### ISSUE THREAD

**Issue by Pegwald** [aura-project/aura#94]
Weaving skill is working well as far as I can see, but I noticed it won't work when you try to make something with the loom. When equipped with Regular Silk Weaving Gloves and trying to make silk, there will be no success, but also no item consumption. You can stand there forever trying to make silk, but in the end you will have nothing else but a waste of time.. ^^''

**Comment by QewQew** [comment]
The code assumes the "tool" will always be in the right hand, and hence only checks the right hand. However the tool for weaving silk is in the gloves pocket. Hence, it fails the check tool test (why doesn't the complete method use CheckTools()?).

Weaving other items like fabric should work just fine, since no tool is required,
